('Mountain peaks of Canada', '/wiki/Mountain_peaks_of_Canada'),
('Mountain', '/wiki/Mountain'),
('Canada', '/wiki/Canada'),
('British Columbia', '/wiki/British_Columbia'),
('Alberta', '/wiki/Alberta'),
('Yukon', '/wiki/Yukon'),
('Canadian Rockies', '/wiki/Canadian_Rockies'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Mount Logan', '/wiki/Mount_Logan'),
('Beatrice Peak', '/wiki/Beatrice_Peak'),
('Cascade Mountain (Alberta)', '/wiki/Cascade_Mountain_(Alberta)'),
('Castle Mountain', '/wiki/Castle_Mountain'),
('Copper Mountain (Alberta)', '/wiki/Copper_Mountain_(Alberta)'),
('Crowfoot Mountain (Alberta)', '/wiki/Crowfoot_Mountain_(Alberta)'),
('Crowsnest Mountain', '/wiki/Crowsnest_Mountain'),
('Deltaform Mountain', '/wiki/Deltaform_Mountain'),
('Diadem Peak', '/wiki/Diadem_Peak'),
('Fairview Mountain (Alberta)', '/wiki/Fairview_Mountain_(Alberta)'),
('Fossil Mountain (Alberta)', '/wiki/Fossil_Mountain_(Alberta)'),
('Gibraltar Mountain (Alberta)', '/wiki/Gibraltar_Mountain_(Alberta)'),
('Gong Peak', '/wiki/Gong_Peak'),
('Grotto Mountain', '/wiki/Grotto_Mountain'),
('Ha Ling Peak', '/wiki/Ha_Ling_Peak'),
('Haiduk Peak', '/wiki/Haiduk_Peak'),
('Heart Mountain (Alberta)', '/wiki/Heart_Mountain_(Alberta)'),
('Howse Peak', '/wiki/Howse_Peak'),
('Isabelle Peak', '/wiki/Isabelle_Peak'),
('Jumpingpound Mountain', '/wiki/Jumpingpound_Mountain'),
('King Edward Peak', '/wiki/King_Edward_Peak'),
('Little Alberta', '/wiki/Little_Alberta'),
('Moose Mountain (Alberta)', '/wiki/Moose_Mountain_(Alberta)'),
('Mount Adam Joachim', '/wiki/Mount_Adam_Joachim'),
('Mount Alberta', '/wiki/Mount_Alberta'),
('Mount Andromeda (Alberta)', '/wiki/Mount_Andromeda_(Alberta)'),
('Mount Arethusa', '/wiki/Mount_Arethusa'),
('Mount Assiniboine', '/wiki/Mount_Assiniboine'),
('Mount Athabasca', '/wiki/Mount_Athabasca'),
('Mount Aylmer', '/wiki/Mount_Aylmer'),
('Mount Babel (Alberta)', '/wiki/Mount_Babel_(Alberta)'),
('Mount Baker (Waputik Mountains)', '/wiki/Mount_Baker_(Waputik_Mountains)'),
('Mount Baldy (Alberta)', '/wiki/Mount_Baldy_(Alberta)'),
('Mount Ball', '/wiki/Mount_Ball'),
('Mount Blakiston', '/wiki/Mount_Blakiston'),
('Mount Brazeau', '/wiki/Mount_Brazeau'),
('Mount Charles Stewart', '/wiki/Mount_Charles_Stewart'),
('Mount Chephren', '/wiki/Mount_Chephren'),
('Mount Chester', '/wiki/Mount_Chester'),
('Mount Chown', '/wiki/Mount_Chown'),
('Mount Columbia (Canada)', '/wiki/Mount_Columbia_(Canada)'),
('Mount Confederation', '/wiki/Mount_Confederation'),
('Mount Cory (Alberta)', '/wiki/Mount_Cory_(Alberta)'),
('Mount Cromwell', '/wiki/Mount_Cromwell'),
('Mount Edith Cavell', '/wiki/Mount_Edith_Cavell'),
('Mount Engelhard', '/wiki/Mount_Engelhard'),
('Mount Forbes', '/wiki/Mount_Forbes'),
('Mount Fryatt', '/wiki/Mount_Fryatt'),
('Mount Galatea', '/wiki/Mount_Galatea'),
('Mount Galwey', '/wiki/Mount_Galwey'),
('Mount Gec', '/wiki/Mount_Gec'),
('Mount Girouard', '/wiki/Mount_Girouard'),
('Mount Hector (Alberta)', '/wiki/Mount_Hector_(Alberta)'),
('Mount Hungabee', '/wiki/Mount_Hungabee'),
('Mount Inglismaldie', '/wiki/Mount_Inglismaldie'),
('Mount Joffre', '/wiki/Mount_Joffre'),
('Mount John Laurie', '/wiki/Mount_John_Laurie'),
('Mount Julian (Alberta)', '/wiki/Mount_Julian_(Alberta)'),
('Mount King Edward', '/wiki/Mount_King_Edward'),
('Mount Kitchener', '/wiki/Mount_Kitchener'),
('Mount Lady Macdonald', '/wiki/Mount_Lady_Macdonald'),
('Mount Lawrence Grassi', '/wiki/Mount_Lawrence_Grassi'),
('Mount Lefroy', '/wiki/Mount_Lefroy'),
('Mount Louis', '/wiki/Mount_Louis'),
('Mount McGuire (Alberta)', '/wiki/Mount_McGuire_(Alberta)'),
('Mount Michener', '/wiki/Mount_Michener'),
('Mount Mitchell (Alberta)', '/wiki/Mount_Mitchell_(Alberta)'),
('Mount Morden Long', '/wiki/Mount_Morden_Long'),
('Mount Nelson (Alberta)', '/wiki/Mount_Nelson_(Alberta)'),
('Mount Niblock', '/wiki/Mount_Niblock'),
('Mount Palmer (Alberta)', '/wiki/Mount_Palmer_(Alberta)'),
('Mount Peechee', '/wiki/Mount_Peechee'),
('Mount Putnik', '/wiki/Mount_Putnik'),
('Mount Rae', '/wiki/Mount_Rae'),
('Mount Richardson (Alberta)', '/wiki/Mount_Richardson_(Alberta)'),
('Mount Rundle', '/wiki/Mount_Rundle'),
('Mount St. Piran', '/wiki/Mount_St._Piran'),
('Mount Saskatchewan (Alberta)', '/wiki/Mount_Saskatchewan_(Alberta)'),
('Mount Smythe', '/wiki/Mount_Smythe'),
('Mount Temple (Alberta)', '/wiki/Mount_Temple_(Alberta)'),
('Mount Weiss', '/wiki/Mount_Weiss'),
('Mount Whyte', '/wiki/Mount_Whyte'),
('Mount Woolley', '/wiki/Mount_Woolley'),
('Mushroom Peak', '/wiki/Mushroom_Peak'),
('North Twin Peak', '/wiki/North_Twin_Peak'),
('Panther Mountain (Alberta)', '/wiki/Panther_Mountain_(Alberta)'),
('Peyto Peak', '/wiki/Peyto_Peak'),
('Pika Peak', '/wiki/Pika_Peak'),
('Pilot Mountain (Alberta)', '/wiki/Pilot_Mountain_(Alberta)'),
('Princess Margaret Mountain', '/wiki/Princess_Margaret_Mountain'),
('Ptarmigan Peak (Alberta)', '/wiki/Ptarmigan_Peak_(Alberta)'),
('Pyramid Mountain (Alberta)', '/wiki/Pyramid_Mountain_(Alberta)'),
('Redoubt Mountain', '/wiki/Redoubt_Mountain'),
('Saint Nicholas Peak (Canada)', '/wiki/Saint_Nicholas_Peak_(Canada)'),
('Sentinel Peak (Alberta)', '/wiki/Sentinel_Peak_(Alberta)'),
('Snow Dome (Canada)', '/wiki/Snow_Dome_(Canada)'),
('South Twin Peak', '/wiki/South_Twin_Peak'),
("Squaw's Tit", '/wiki/Squaw%27s_Tit'),
('Storm Mountain (Alberta)', '/wiki/Storm_Mountain_(Alberta)'),
('Stutfield Peak', '/wiki/Stutfield_Peak'),
('Sulphur Mountain (Alberta)', '/wiki/Sulphur_Mountain_(Alberta)'),
('Sunwapta Peak', '/wiki/Sunwapta_Peak'),
('The Finger (Alberta)', '/wiki/The_Finger_(Alberta)'),
('The Fortress (Alberta)', '/wiki/The_Fortress_(Alberta)'),
('Thorington Tower', '/wiki/Thorington_Tower'),
('North Twin Peak', '/wiki/North_Twin_Peak'),
('Turtle Mountain (Alberta)', '/wiki/Turtle_Mountain_(Alberta)'),
('Frank Slide', '/wiki/Frank_Slide'),
('Warwick Mountain', '/wiki/Warwick_Mountain'),
('Atlin Mountain', '/wiki/Atlin_Mountain'),
('Mount Adrian', '/wiki/Mount_Adrian'),
('Mount Albert Edward (British Columbia)', '/wiki/Mount_Albert_Edward_(British_Columbia)'),
('Mount Alfred', '/wiki/Mount_Alfred'),
('Anarchist Mountain', '/wiki/Anarchist_Mountain'),
('Mount Arrowsmith', '/wiki/Mount_Arrowsmith'),
('Mount Assiniboine', '/wiki/Mount_Assiniboine'),
('Mount Ball', '/wiki/Mount_Ball'),
('Battle Mountain (British Columbia)', '/wiki/Battle_Mountain_(British_Columbia)'),
('Beatrice Peak', '/wiki/Beatrice_Peak'),
('Birkenhead Peak', '/wiki/Birkenhead_Peak'),
('Mount Bishop (Elk Range)', '/wiki/Mount_Bishop_(Elk_Range)'),
('Botanie Mountain', '/wiki/Botanie_Mountain'),
('Mount Boucherie', '/wiki/Mount_Boucherie'),
('Mount Brown (British Columbia)', '/wiki/Mount_Brown_(British_Columbia)'),
('Mount Bryce', '/wiki/Mount_Bryce'),
('Mount Burgess', '/wiki/Mount_Burgess'),
('Canadian Border Peak', '/wiki/Canadian_Border_Peak'),
('Mount Cayley', '/wiki/Mount_Cayley'),
('Mount Celeste', '/wiki/Mount_Celeste'),
('Chatsquot Mountain', '/wiki/Chatsquot_Mountain'),
('Chutine Peak', '/wiki/Chutine_Peak'),
('Mount Collie', '/wiki/Mount_Collie'),
('Mount Colonel Foster', '/wiki/Mount_Colonel_Foster'),
('Mount Columbia (Canada)', '/wiki/Mount_Columbia_(Canada)'),
('Mount Cronin', '/wiki/Mount_Cronin'),
('Crown Mountain (Vancouver Island, British Columbia)', '/wiki/Crown_Mountain_(Vancouver_Island,_British_Columbia)'),
('Cypress Peak', '/wiki/Cypress_Peak'),
('Deltaform Mountain', '/wiki/Deltaform_Mountain'),
('Devils Paw', '/wiki/Devils_Paw'),
('Doom Mountain', '/wiki/Doom_Mountain'),
('Dunn Peak', '/wiki/Dunn_Peak'),
('Mount Edziza', '/wiki/Mount_Edziza'),
('El Piveto Mountain', '/wiki/El_Piveto_Mountain'),
('Elkhorn Mountain', '/wiki/Elkhorn_Mountain'),
('Mount Elliott (British Columbia)', '/wiki/Mount_Elliott_(British_Columbia)'),
('Mount Fairweather', '/wiki/Mount_Fairweather'),
('Mount Farnham', '/wiki/Mount_Farnham'),
('Mount Field (British Columbia)', '/wiki/Mount_Field_(British_Columbia)'),
('Fissile Peak', '/wiki/Fissile_Peak'),
('Mount Fromme', '/wiki/Mount_Fromme'),
('Mount Garibaldi', '/wiki/Mount_Garibaldi'),
('Garnet Peak', '/wiki/Garnet_Peak'),
('Mount George V', '/wiki/Mount_George_V'),
('Goat Mountain (Vancouver, British Columbia)', '/wiki/Goat_Mountain_(Vancouver,_British_Columbia)'),
('Vancouver Island', '/wiki/Vancouver_Island'),
('Mount Good Hope', '/wiki/Mount_Good_Hope'),
('Mount Goodsir', '/wiki/Mount_Goodsir'),
('Grouse Mountain', '/wiki/Grouse_Mountain'),
('Haiduk Peak', '/wiki/Haiduk_Peak'),
('Hermitage Peak (British Columbia)', '/wiki/Hermitage_Peak_(British_Columbia)'),
('Hkusam Mountain', '/wiki/Hkusam_Mountain'),
('Howse Peak', '/wiki/Howse_Peak'),
('Howser Spire', '/wiki/Howser_Spire'),
('Howson Peak', '/wiki/Howson_Peak'),
('Hudson Bay Mountain', '/wiki/Hudson_Bay_Mountain'),
('Iceberg Peak', '/wiki/Iceberg_Peak'),
('Isabelle Peak', '/wiki/Isabelle_Peak'),
('Jackass Mountain', '/wiki/Jackass_Mountain'),
('Kates Needle', '/wiki/Kates_Needle'),
('King Island (British Columbia)', '/wiki/King_Island_(British_Columbia)'),
('Kings Peak (British Columbia)', '/wiki/Kings_Peak_(British_Columbia)'),
('Kispiox Mountain', '/wiki/Kispiox_Mountain'),
('Lavender Peak (British Columbia)', '/wiki/Lavender_Peak_(British_Columbia)'),
('Mount Lester Pearson', '/wiki/Mount_Lester_Pearson'),
('Luna Peak (British Columbia)', '/wiki/Luna_Peak_(British_Columbia)'),
('Maple Mountain (British Columbia)', '/wiki/Maple_Mountain_(British_Columbia)'),
('Mount Matheson', '/wiki/Mount_Matheson'),
('Monarch Mountain', '/wiki/Monarch_Mountain'),
('Monmouth Mountain', '/wiki/Monmouth_Mountain'),
('Mount Hosmer (British Columbia)', '/wiki/Mount_Hosmer_(British_Columbia)'),
('Mount Hugh Neave', '/wiki/Mount_Hugh_Neave'),
('Mount Hungabee', '/wiki/Mount_Hungabee'),
('Mount Joffre', '/wiki/Mount_Joffre'),
('Mount Judge Howay', '/wiki/Mount_Judge_Howay'),
('Mount K2 (Alberta)', '/wiki/Mount_K2_(Alberta)'),
('Mount Kain', '/wiki/Mount_Kain'),
('Mount King Edward', '/wiki/Mount_King_Edward'),
('Mount Lefroy', '/wiki/Mount_Lefroy'),
('Mount Macdonald', '/wiki/Mount_Macdonald'),
('Mount Mackenzie King', '/wiki/Mount_Mackenzie_King'),
('Mount McArthur (British Columbia)', '/wiki/Mount_McArthur_(British_Columbia)'),
('Mount McBride', '/wiki/Mount_McBride'),
('Mount Meager', '/wiki/Mount_Meager'),
('Mount Moresby', '/wiki/Mount_Moresby'),
('Moresby Island', '/wiki/Moresby_Island'),
('Mount Munday', '/wiki/Mount_Munday'),
('Mount Odin (British Columbia)', '/wiki/Mount_Odin_(British_Columbia)'),
('Mount Perseus (British Columbia)', '/wiki/Mount_Perseus_(British_Columbia)'),
('Mount Pierre Elliott Trudeau', '/wiki/Mount_Pierre_Elliott_Trudeau'),
('Mount Price (British Columbia)', '/wiki/Mount_Price_(British_Columbia)'),
('Mount Priestley (British Columbia)', '/wiki/Mount_Priestley_(British_Columbia)'),
('Mount Raleigh', '/wiki/Mount_Raleigh'),
('Mount Ratz', '/wiki/Mount_Ratz'),
('Mount Robson', '/wiki/Mount_Robson'),
('Mount Russell (British Columbia)', '/wiki/Mount_Russell_(British_Columbia)'),
('Mount Saugstad', '/wiki/Mount_Saugstad'),
('Mount Seymour', '/wiki/Mount_Seymour'),
('Mount Silverthrone', '/wiki/Mount_Silverthrone'),
('Mount Sir Allan MacNab', '/wiki/Mount_Sir_Allan_MacNab'),
('Mount Sir Sandford', '/wiki/Mount_Sir_Sandford'),
('Selkirk Mountains', '/wiki/Selkirk_Mountains'),
('Mount Sir Wilfrid Laurier', '/wiki/Mount_Sir_Wilfrid_Laurier'),
('Cariboo Mountains', '/wiki/Cariboo_Mountains'),
('Mount Stanley Baldwin', '/wiki/Mount_Stanley_Baldwin'),
('Mount Stephen', '/wiki/Mount_Stephen'),
('Nahlin Mountain', '/wiki/Nahlin_Mountain'),
('Mount Penrose', '/wiki/Mount_Penrose'),
('Pilot Mountain (British Columbia)', '/wiki/Pilot_Mountain_(British_Columbia)'),
('Pukeashun Mountain', '/wiki/Pukeashun_Mountain'),
('Mount Queen Bess', '/wiki/Mount_Queen_Bess'),
('Mount Quincy Adams (Fairweather Range)', '/wiki/Mount_Quincy_Adams_(Fairweather_Range)'),
('Rambler Peak', '/wiki/Rambler_Peak'),
('Razorback Mountain (British Columbia)', '/wiki/Razorback_Mountain_(British_Columbia)'),
('Razorback Mountain', '/wiki/Razorback_Mountain'),
('Ringrose Peak', '/wiki/Ringrose_Peak'),
('Rugged Mountain', '/wiki/Rugged_Mountain'),
('Sharktooth Mountain', '/wiki/Sharktooth_Mountain'),
('Shedin Peak', '/wiki/Shedin_Peak'),
('Silvertip Mountain', '/wiki/Silvertip_Mountain'),
('Skihist Mountain', '/wiki/Skihist_Mountain'),
('Slesse Mountain', '/wiki/Slesse_Mountain'),
('Snow Dome (Canada)', '/wiki/Snow_Dome_(Canada)'),
('Spatsizi Mountain', '/wiki/Spatsizi_Mountain'),
('Stanley Peak (Ball Range)', '/wiki/Stanley_Peak_(Ball_Range)'),
('Stawamus Chief', '/wiki/Stawamus_Chief'),
('Mount Stephens (British Columbia)', '/wiki/Mount_Stephens_(British_Columbia)'),
('Mount Tabor (British Columbia)', '/wiki/Mount_Tabor_(British_Columbia)'),
('Mount Tantalus', '/wiki/Mount_Tantalus'),
('Taseko Mountain', '/wiki/Taseko_Mountain'),
('Mount Tatlow', '/wiki/Mount_Tatlow'),
('Mount Thomlinson', '/wiki/Mount_Thomlinson'),
('Mount Tiedemann', '/wiki/Mount_Tiedemann'),
('Mount Tod', '/wiki/Mount_Tod'),
('Tower Mountain (British Columbia)', '/wiki/Tower_Mountain_(British_Columbia)'),
('Trophy Mountain', '/wiki/Trophy_Mountain'),
('Tsaydaychuz Peak', '/wiki/Tsaydaychuz_Peak'),
('The Black Tusk', '/wiki/The_Black_Tusk'),
('Unnecessary Mountain', '/wiki/Unnecessary_Mountain'),
('Victoria Peak (British Columbia)', '/wiki/Victoria_Peak_(British_Columbia)'),
('Mount Waddington', '/wiki/Mount_Waddington'),
('Coast Mountains', '/wiki/Coast_Mountains'),
('Wapta Mountain', '/wiki/Wapta_Mountain'),
('Mount Warburton Pike', '/wiki/Mount_Warburton_Pike'),
('Warden Peak', '/wiki/Warden_Peak'),
('Wedge Mountain', '/wiki/Wedge_Mountain'),
('Welch Peak', '/wiki/Welch_Peak'),
('Whitecap Mountain', '/wiki/Whitecap_Mountain'),
('Whitehorn Mountain (British Columbia)', '/wiki/Whitehorn_Mountain_(British_Columbia)'),
('Whiting Peak (British Columbia)', '/wiki/Whiting_Peak_(British_Columbia)'),
('Mount Williams (Canada)', '/wiki/Mount_Williams_(Canada)'),
('Wiwaxy Peak', '/wiki/Wiwaxy_Peak'),
('Mount Work', '/wiki/Mount_Work'),
('Yak Peak', '/wiki/Yak_Peak'),
('Baldy Mountain (Manitoba)', '/wiki/Baldy_Mountain_(Manitoba)'),
('Hart Mountain (Manitoba)', '/wiki/Hart_Mountain_(Manitoba)'),
('Porcupine Hills', '/wiki/Porcupine_Hills'),
('Mount Carleton', '/wiki/Mount_Carleton'),
('The Maritimes', '/wiki/The_Maritimes'),
('Big Bald Mountain (New Brunswick)', '/wiki/Big_Bald_Mountain_(New_Brunswick)'),
('Christmas Mountains', '/wiki/Christmas_Mountains'),
('Christmas', '/wiki/Christmas'),
('Notre Dame Mountains', '/wiki/Notre_Dame_Mountains'),
('Colonels Mountain (New Brunswick)', '/wiki/Colonels_Mountain_(New_Brunswick)'),
('Sugarloaf Mountain (New Brunswick)', '/wiki/Sugarloaf_Mountain_(New_Brunswick)'),
('Crabbe Mountain', '/wiki/Crabbe_Mountain'),
('Poley Mountain', '/wiki/Poley_Mountain'),
('Brave Mountain', '/wiki/Brave_Mountain'),
('Kaumajet Mountains', '/wiki/Kaumajet_Mountains'),
('The Cabox', '/wiki/The_Cabox'),
('Lewis Hills', '/wiki/Lewis_Hills'),
('Cirque Mountain', '/wiki/Cirque_Mountain'),
('Gros Morne, Newfoundland', '/wiki/Gros_Morne,_Newfoundland'),
('Mealy Mountains', '/wiki/Mealy_Mountains'),
('Torngat Mountains', '/wiki/Torngat_Mountains'),
('Atlantic Canada', '/wiki/Atlantic_Canada'),
('Mount Musgrave', '/wiki/Mount_Musgrave'),
('Peter Snout', '/wiki/Peter_Snout'),
('Pic a Tenerife', '/wiki/Pic_a_Tenerife'),
('Franklin Mountains (Northwest Territories)', '/wiki/Franklin_Mountains_(Northwest_Territories)'),
('Mount Nirvana', '/wiki/Mount_Nirvana'),
('Mackenzie Mountains', '/wiki/Mackenzie_Mountains'),
('Northwest Territories', '/wiki/Northwest_Territories'),
('Mount Sir James MacBrien', '/wiki/Mount_Sir_James_MacBrien'),
('North Mountain (Nova Scotia)', '/wiki/North_Mountain_(Nova_Scotia)'),
('Nuttby Mountain', '/wiki/Nuttby_Mountain'),
('South Mountain (Nova Scotia)', '/wiki/South_Mountain_(Nova_Scotia)'),
('White Hill (Nova Scotia)', '/wiki/White_Hill_(Nova_Scotia)'),
('Cape Breton Highlands', '/wiki/Cape_Breton_Highlands'),
('Angilaaq Mountain', '/wiki/Angilaaq_Mountain'),
('Bylot Island', '/wiki/Bylot_Island'),
('Angna Mountain', '/wiki/Angna_Mountain'),
('Arrowhead Mountain', '/wiki/Arrowhead_Mountain'),
('Barbeau Peak', '/wiki/Barbeau_Peak'),
('Ellesmere Island', '/wiki/Ellesmere_Island'),
('Nunavut', '/wiki/Nunavut'),
('Breidablik Peak', '/wiki/Breidablik_Peak'),
('Commonwealth Mountain', '/wiki/Commonwealth_Mountain'),
('Devon Ice Cap', '/wiki/Devon_Ice_Cap'),
('Devon Island', '/wiki/Devon_Island'),
('Highpointer Peak', '/wiki/Highpointer_Peak'),
('Kisimngiuqtuq Peak', '/wiki/Kisimngiuqtuq_Peak'),
('Nunavut', '/wiki/Nunavut'),
('Melville Island (Northwest Territories and Nunavut)', '/wiki/Melville_Island_(Northwest_Territories_and_Nunavut)'),
('Melville Island (Northwest Territories and Nunavut)', '/wiki/Melville_Island_(Northwest_Territories_and_Nunavut)'),
('Midnight Sun Peak', '/wiki/Midnight_Sun_Peak'),
('Mount Arthur (Nunavut)', '/wiki/Mount_Arthur_(Nunavut)'),
('Mount Asgard', '/wiki/Mount_Asgard'),
('Mount Ayles', '/wiki/Mount_Ayles'),
('Mount Baldr', '/wiki/Mount_Baldr'),
('Mount Battle', '/wiki/Mount_Battle'),
('Mount Beaufort', '/wiki/Mount_Beaufort'),
('Mount Biederbick', '/wiki/Mount_Biederbick'),
('Mount Eugene', '/wiki/Mount_Eugene'),
('Mount Odin', '/wiki/Mount_Odin'),
('Baffin Island', '/wiki/Baffin_Island'),
('Mount Oxford (Nunavut)', '/wiki/Mount_Oxford_(Nunavut)'),
('Mount Thor', '/wiki/Mount_Thor'),
('Mount Whisler', '/wiki/Mount_Whisler'),
('Outlook Peak', '/wiki/Outlook_Peak'),
('Axel Heiberg Island', '/wiki/Axel_Heiberg_Island'),
('Qiajivik Mountain', '/wiki/Qiajivik_Mountain'),
('Sillem Island', '/wiki/Sillem_Island'),
('Stokes Mountain', '/wiki/Stokes_Mountain'),
('Torngarsoak Mountain', '/wiki/Torngarsoak_Mountain'),
('Ukpik Peak', '/wiki/Ukpik_Peak'),
('Victoria Island (Canada)', '/wiki/Victoria_Island_(Canada)'),
('Victoria Island (Canada)', '/wiki/Victoria_Island_(Canada)'),
('White Crown Mountain', '/wiki/White_Crown_Mountain'),
('Caribou Mountain (Temagami)', '/wiki/Caribou_Mountain_(Temagami)'),
('High Rock (Ontario)', '/wiki/High_Rock_(Ontario)'),
('Ishpatina Ridge', '/wiki/Ishpatina_Ridge'),
('Maple Mountain (Ontario)', '/wiki/Maple_Mountain_(Ontario)'),
('Mount McKay', '/wiki/Mount_McKay'),
('Rib Mountain (Ontario)', '/wiki/Rib_Mountain_(Ontario)'),
('Tip Top Mountain', '/wiki/Tip_Top_Mountain'),
('Mont Brome', '/wiki/Mont_Brome'),
('Mount Caubvick', '/wiki/Mount_Caubvick'),
('Mont Jacques-Cartier', '/wiki/Mont_Jacques-Cartier'),
('Laurentian Mountains', '/wiki/Laurentian_Mountains'),
('Mont Saint-Grégoire', '/wiki/Mont_Saint-Gr%C3%A9goire'),
('Mont Saint-Hilaire', '/wiki/Mont_Saint-Hilaire'),
('Mount Babel (Quebec)', '/wiki/Mount_Babel_(Quebec)'),
('Mount Royal', '/wiki/Mount_Royal'),
('Mount Albert (Quebec)', '/wiki/Mount_Albert_(Quebec)'),
('Mount Valin', '/wiki/Mount_Valin'),
('Mont Mégantic', '/wiki/Mont_M%C3%A9gantic'),
('Mont Orford', '/wiki/Mont_Orford'),
("Mont Owl's Head", '/wiki/Mont_Owl%27s_Head'),
('Mont Sutton', '/wiki/Mont_Sutton'),
('Cypress Hills (Canada)', '/wiki/Cypress_Hills_(Canada)'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Avalanche Peak (Yukon)', '/wiki/Avalanche_Peak_(Yukon)'),
('Pelly Mountains', '/wiki/Pelly_Mountains'),
('Keele Peak', '/wiki/Keele_Peak'),
('Mackenzie Mountains', '/wiki/Mackenzie_Mountains'),
('King Peak (Yukon)', '/wiki/King_Peak_(Yukon)'),
('McArthur Peak', '/wiki/McArthur_Peak'),
('Mount Alverstone', '/wiki/Mount_Alverstone'),
('Mount Augusta', '/wiki/Mount_Augusta'),
('Mount Cook (Saint Elias Mountains)', '/wiki/Mount_Cook_(Saint_Elias_Mountains)'),
('Mount Frank Rae', '/wiki/Mount_Frank_Rae'),
('Mount Hubbard', '/wiki/Mount_Hubbard'),
('Mount Kennedy', '/wiki/Mount_Kennedy'),
('Mount Logan', '/wiki/Mount_Logan'),
('Mount Lucania', '/wiki/Mount_Lucania'),
('Mount Macdonald', '/wiki/Mount_Macdonald'),
('Mount Saint Elias', '/wiki/Mount_Saint_Elias'),
('Mount Saskatchewan (Yukon)', '/wiki/Mount_Saskatchewan_(Yukon)'),
('Mount Slaggard', '/wiki/Mount_Slaggard'),
('Mount Steele', '/wiki/Mount_Steele'),
('Mount Strickland', '/wiki/Mount_Strickland'),
('Mount Vancouver', '/wiki/Mount_Vancouver'),
('Mount Walsh', '/wiki/Mount_Walsh'),
('Mount Wood (Yukon)', '/wiki/Mount_Wood_(Yukon)'),
('Portal:Geography', '/wiki/Portal:Geography'),
('Portal:North America', '/wiki/Portal:North_America'),
('Portal:Canada', '/wiki/Portal:Canada'),
('Portal:Geography of Canada', '/wiki/Portal:Geography_of_Canada'),
('Portal:Mountains', '/wiki/Portal:Mountains'),
('Book:Canada', '/wiki/Book:Canada'),
('Outline of Canada', '/wiki/Outline_of_Canada'),
('Bibliography of Canada', '/wiki/Bibliography_of_Canada'),
('Index of Canada-related articles', '/wiki/Index_of_Canada-related_articles'),
('Canada', '/wiki/Canada'),
('Geography of Canada', '/wiki/Geography_of_Canada'),
('Physical geography', '/wiki/Physical_geography'),
('Topography', '/wiki/Topography'),
('Topographic isolation', '/wiki/Topographic_isolation'),
('Topographic prominence', '/wiki/Topographic_prominence'),
('Lists of mountains by region', '/wiki/Lists_of_mountains_by_region'),
('Mountain peaks of Canada', '/wiki/Mountain_peaks_of_Canada'),
('Atlas of Canada', '/wiki/Atlas_of_Canada'),
('Template:Canada topics', '/wiki/Template:Canada_topics'),
('Template talk:Canada topics', '/wiki/Template_talk:Canada_topics'),
('Canada', '/wiki/Canada'),
('History of Canada', '/wiki/History_of_Canada'),
('Timeline of Canadian history', '/wiki/Timeline_of_Canadian_history'),
('New France', '/wiki/New_France'),
('Canada under British rule', '/wiki/Canada_under_British_rule'),
('Canada in the World Wars and Interwar Years', '/wiki/Canada_in_the_World_Wars_and_Interwar_Years'),
('History of Canada (1945–60)', '/wiki/History_of_Canada_(1945%E2%80%9360)'),
('History of Canada (1960–81)', '/wiki/History_of_Canada_(1960%E2%80%9381)'),
('History of Canada (1982–92)', '/wiki/History_of_Canada_(1982%E2%80%9392)'),
('History of Canada (1992–present)', '/wiki/History_of_Canada_(1992%E2%80%93present)'),
('Outline of Canada', '/wiki/Outline_of_Canada#History_of_Canada'),
('Constitutional history of Canada', '/wiki/Constitutional_history_of_Canada'),
('Economic history of Canada', '/wiki/Economic_history_of_Canada'),
('Name of Canada', '/wiki/Name_of_Canada'),
('Former colonies and territories in Canada', '/wiki/Former_colonies_and_territories_in_Canada'),
('History of immigration to Canada', '/wiki/History_of_immigration_to_Canada'),
('Military history of Canada', '/wiki/Military_history_of_Canada'),
('History of monarchy in Canada', '/wiki/History_of_monarchy_in_Canada'),
('National Historic Sites of Canada', '/wiki/National_Historic_Sites_of_Canada'),
('Persons of National Historic Significance', '/wiki/Persons_of_National_Historic_Significance'),
('Territorial evolution of Canada', '/wiki/Territorial_evolution_of_Canada'),
('History of Canadian women', '/wiki/History_of_Canadian_women'),
('Provinces and territories of Canada', '/wiki/Provinces_and_territories_of_Canada'),
('Alberta', '/wiki/Alberta'),
('British Columbia', '/wiki/British_Columbia'),
('Manitoba', '/wiki/Manitoba'),
('New Brunswick', '/wiki/New_Brunswick'),
('Newfoundland and Labrador', '/wiki/Newfoundland_and_Labrador'),
('Nova Scotia', '/wiki/Nova_Scotia'),
('Ontario', '/wiki/Ontario'),
('Prince Edward Island', '/wiki/Prince_Edward_Island'),
('Quebec', '/wiki/Quebec'),
('Saskatchewan', '/wiki/Saskatchewan'),
('Northwest Territories', '/wiki/Northwest_Territories'),
('Nunavut', '/wiki/Nunavut'),
('Yukon', '/wiki/Yukon'),
('Government of Canada', '/wiki/Government_of_Canada'),
('Law of Canada', '/wiki/Law_of_Canada'),
('Constitution of Canada', '/wiki/Constitution_of_Canada'),
('Monarchy of Canada', '/wiki/Monarchy_of_Canada'),
('Governor General of Canada', '/wiki/Governor_General_of_Canada'),
('Parliament of Canada', '/wiki/Parliament_of_Canada'),
('Senate of Canada', '/wiki/Senate_of_Canada'),
('House of Commons of Canada', '/wiki/House_of_Commons_of_Canada'),
('Prime Minister of Canada', '/wiki/Prime_Minister_of_Canada'),
('Court system of Canada', '/wiki/Court_system_of_Canada'),
('Supreme Court of Canada', '/wiki/Supreme_Court_of_Canada'),
('Canadian Armed Forces', '/wiki/Canadian_Armed_Forces'),
('Municipal government in Canada', '/wiki/Municipal_government_in_Canada'),
('Foreign relations of Canada', '/wiki/Foreign_relations_of_Canada'),
('Law enforcement in Canada', '/wiki/Law_enforcement_in_Canada'),
('Politics of Canada', '/wiki/Politics_of_Canada'),
('Elections in Canada', '/wiki/Elections_in_Canada'),
('LGBT rights in Canada', '/wiki/LGBT_rights_in_Canada'),
('Multiculturalism in Canada', '/wiki/Multiculturalism_in_Canada'),
('Geography of Canada', '/wiki/Geography_of_Canada'),
('Pacific Northwest', '/wiki/Pacific_Northwest'),
('Western Canada', '/wiki/Western_Canada'),
('Great Plains', '/wiki/Great_Plains'),
('Canadian Prairies', '/wiki/Canadian_Prairies'),
('Northern Canada', '/wiki/Northern_Canada'),
('Canadian Shield', '/wiki/Canadian_Shield'),
('Great Lakes region', '/wiki/Great_Lakes_region'),
('Central Canada', '/wiki/Central_Canada'),
('The Maritimes', '/wiki/The_Maritimes'),
('Eastern Canada', '/wiki/Eastern_Canada'),
('Atlantic Canada', '/wiki/Atlantic_Canada'),
('Outline of Canada', '/wiki/Outline_of_Canada#Geography_of_Canada'),
('Fauna of Canada', '/wiki/Fauna_of_Canada'),
('Mountain peaks of Canada', '/wiki/Mountain_peaks_of_Canada'),
('National Parks of Canada', '/wiki/National_Parks_of_Canada'),
('Flora of Canada', '/wiki/Flora_of_Canada'),
('Great Lakes', '/wiki/Great_Lakes'),
('Economy of Canada', '/wiki/Economy_of_Canada'),
('Agriculture in Canada', '/wiki/Agriculture_in_Canada'),
('Banking in Canada', '/wiki/Banking_in_Canada'),
('Bank of Canada', '/wiki/Bank_of_Canada'),
('Canadian dollar', '/wiki/Canadian_dollar'),
('Telecommunications in Canada', '/wiki/Telecommunications_in_Canada'),
('Energy policy of Canada', '/wiki/Energy_policy_of_Canada'),
('Fishing industry in Canada', '/wiki/Fishing_industry_in_Canada'),
('Oil reserves in Canada', '/wiki/Oil_reserves_in_Canada'),
('Toronto Stock Exchange', '/wiki/Toronto_Stock_Exchange'),
('Taxation in Canada', '/wiki/Taxation_in_Canada'),
('Tourism in Canada', '/wiki/Tourism_in_Canada'),
('Transportation in Canada', '/wiki/Transportation_in_Canada'),
('Science and technology in Canada', '/wiki/Science_and_technology_in_Canada'),
('Social programs in Canada', '/wiki/Social_programs_in_Canada'),
('Poverty in Canada', '/wiki/Poverty_in_Canada'),
('Education in Canada', '/wiki/Education_in_Canada'),
('Healthcare in Canada', '/wiki/Healthcare_in_Canada'),
('Crime in Canada', '/wiki/Crime_in_Canada'),
('Canadian values', '/wiki/Canadian_values'),
('Demographics of Canada', '/wiki/Demographics_of_Canada'),
('Outline of Canada', '/wiki/Outline_of_Canada#Demography_of_Canada'),
('Canadians', '/wiki/Canadians'),
('Immigration to Canada', '/wiki/Immigration_to_Canada'),
('Languages of Canada', '/wiki/Languages_of_Canada'),
('Religion in Canada', '/wiki/Religion_in_Canada'),
('Canada 2001 Census', '/wiki/Canada_2001_Census'),
('Canada 2006 Census', '/wiki/Canada_2006_Census'),
('Canada 2011 Census', '/wiki/Canada_2011_Census'),
('Population of Canada', '/wiki/Population_of_Canada'),
('Culture of Canada', '/wiki/Culture_of_Canada'),
('Architecture of Canada', '/wiki/Architecture_of_Canada'),
('Canadian art', '/wiki/Canadian_art'),
('Cinema of Canada', '/wiki/Cinema_of_Canada'),
('Canadian cuisine', '/wiki/Canadian_cuisine'),
('Canadian folklore', '/wiki/Canadian_folklore'),
('Public holidays in Canada', '/wiki/Public_holidays_in_Canada'),
('Canadian identity', '/wiki/Canadian_identity'),
('Canadian literature', '/wiki/Canadian_literature'),
('Music of Canada', '/wiki/Music_of_Canada'),
('Nationalisms in Canada', '/wiki/Nationalisms_in_Canada'),
('Canadian online media', '/wiki/Canadian_online_media'),
('Canadian cultural protectionism', '/wiki/Canadian_cultural_protectionism'),
('Sports in Canada', '/wiki/Sports_in_Canada'),
('Theatre of Canada', '/wiki/Theatre_of_Canada'),
('National symbols of Canada', '/wiki/National_symbols_of_Canada'),
('Arms of Canada', '/wiki/Arms_of_Canada'),
('Canadian royal symbols', '/wiki/Canadian_royal_symbols'),
('Canadian heraldry', '/wiki/Canadian_heraldry'),
('Index of Canada-related articles', '/wiki/Index_of_Canada-related_articles'),
('Outline of Canada', '/wiki/Outline_of_Canada'),
('Bibliography of Canada', '/wiki/Bibliography_of_Canada'),
('Historiography of Canada', '/wiki/Historiography_of_Canada'),
('Book:Canada', '/wiki/Book:Canada'),
('Portal:Canada', '/wiki/Portal:Canada'),
('Template:Mountain peaks of North America', '/wiki/Template:Mountain_peaks_of_North_America'),
('Help:Category', '/wiki/Help:Category'),
('Discussion about edits from this IP address [n]', '/wiki/Special:MyTalk'),
('A list of edits made from this IP address [y]', '/wiki/Special:MyContributions'),
('You are encouraged to create an account and log in; however, it is not mandatory', '/w/index.php?title=Special:CreateAccount&returnto=List+of+mountains+of+Canada'),
("You're encouraged to log in; however, it's not mandatory. [o]", '/w/index.php?title=Special:UserLogin&returnto=List+of+mountains+of+Canada'),
('Visit the main page [z]', '/wiki/Main_Page'),
('Guides to browsing Wikipedia', '/wiki/Portal:Contents'),
('Featured content – the best of Wikipedia', '/wiki/Portal:Featured_content'),
('Find background information on current events', '/wiki/Portal:Current_events'),
('Load a random article [x]', '/wiki/Special:Random'),
('Support us', 'https://donate.wikimedia.org/wiki/Special:FundraiserRedirector?utm_source=donate&utm_medium=sidebar&utm_campaign=C13_en.wikipedia.org&uselang=en'),
('Visit the Wikipedia store', '//shop.wikimedia.org'),
('Guidance on how to use and edit Wikipedia', '/wiki/Help:Contents'),
('A list of recent changes in the wiki [r]', '/wiki/Special:RecentChanges'),
('A list of all special pages [q]', '/wiki/Special:SpecialPages'),
('Link to connected data repository item [g]', 'https://www.wikidata.org/wiki/Special:EntityPage/Q1834024'),
