mountain_names = [('Mount Everest', '/wiki/Mount_Everest'),
('Nepal', '/wiki/Geography_of_Nepal'),
('K2', '/wiki/K2'),
('Kangchenjunga', '/wiki/Kangchenjunga'),
('Lhotse', '/wiki/Lhotse'),
('Makalu', '/wiki/Makalu'),
('Cho Oyu', '/wiki/Cho_Oyu'),
('Dhaulagiri', '/wiki/Dhaulagiri'),
('Manaslu', '/wiki/Manaslu'),
('Nanga Parbat', '/wiki/Nanga_Parbat'),
('Annapurna', '/wiki/Annapurna'),
('Gasherbrum I', '/wiki/Gasherbrum_I'),
('Broad Peak', '/wiki/Broad_Peak'),
('Gasherbrum II', '/wiki/Gasherbrum_II'),
('Shishapangma', '/wiki/Shishapangma'),
('Gasherbrum III', '/wiki/Gasherbrum_III'),
('Pakistan', '/wiki/Geography_of_Pakistan'),
('Gyachung Kang', '/wiki/Gyachung_Kang'),
('Nepal', '/wiki/Geography_of_Nepal'),
('Annapurna II', '/wiki/Annapurna'),
('Gasherbrum IV', '/wiki/Gasherbrum_IV'),
('Himalchuli', '/wiki/Himalchuli'),
('Manaslu', '/wiki/Manaslu'),
('Distaghil Sar', '/wiki/Distaghil_Sar'),
('Ngadi Chuli', '/wiki/Ngadi_Chuli'),
('Nuptse', '/wiki/Nuptse'),
('Khunyang Chhish', '/wiki/Khunyang_Chhish'),
('Masherbrum', '/wiki/Masherbrum'),
('Nanda Devi', '/wiki/Nanda_Devi'),
('India', '/wiki/Geography_of_India'),
('Chomo Lonzo', '/wiki/Chomo_Lonzo'),
('Batura Sar', '/wiki/Batura_Sar'),
('Kanjut Sar', '/wiki/Kanjut_Sar'),
('Rakaposhi', '/wiki/Rakaposhi'),
('Namcha Barwa', '/wiki/Namcha_Barwa'),
('Batura II', '/wiki/Batura_II'),
('Kamet', '/wiki/Kamet'),
('Saltoro Kangri', '/wiki/Saltoro_Kangri'),
('Batura III', '/wiki/Batura_III'),
('Kongur Tagh', '/wiki/Kongur_Tagh'),
('Kunlun Mountains', '/wiki/Kunlun_Mountains'),
('Jannu', '/wiki/Jannu'),
('Molamenqing', '/wiki/Molamenqing'),
('Shishapangma', '/wiki/Shishapangma'),
('Gurla Mandhata', '/wiki/Gurla_Mandhata'),
('Tirich Mir', '/wiki/Tirich_Mir'),
('Hindu Kush', '/wiki/Hindu_Kush'),
('Saser Kangri', '/wiki/Saser_Kangri'),
('Chogolisa', '/wiki/Chogolisa'),
('Shispare', '/wiki/Shispare'),
('Silberzacken', '/wiki/Silberzacken'),
('Batura IV', '/w/index.php?title=Batura_IV&action=edit&redlink=1'),
('Changtse', '/wiki/Changtse'),
('Trivor', '/wiki/Trivor'),
('Gangkhar Puensum', '/wiki/Gangkhar_Puensum'),
('Gongga Shan', '/wiki/Gongga_Shan'),
('Daxue Shan', '/wiki/Daxue_Mountains'),
('Sichuan', '/wiki/Sichuan'),
('Annapurna III', '/wiki/Annapurna'),
('Kula Kangri', '/wiki/Kula_Kangri'),
('Chogolisa II', '/wiki/Chogolisa'),
('Muztagh Ata', '/wiki/Muztagh_Ata'),
('Kongur Tagh', '/wiki/Kongur_Tagh'),
('Skyang Kangri', '/wiki/Skyang_Kangri'),
('Karakoram', '/wiki/Karakoram'),
('Liankang Kangri', '/wiki/Liankang_Kangri'),
('Himalayas', '/wiki/Himalayas'),
('Yukshin Gardan Sar', '/wiki/Yukshin_Gardan_Sar'),
('Annapurna IV', '/wiki/Annapurna'),
('Mamostong Kangri', '/wiki/Mamostong_Kangri'),
('Ismoil Somoni Peak', '/wiki/Ismoil_Somoni_Peak'),
('Pamir Mountains', '/wiki/Pamir_Mountains'),
('Tajikistan', '/wiki/Geography_of_Tajikistan'),
('Noshaq', '/wiki/Noshaq'),
('Hindu Kush', '/wiki/Hindu_Kush'),
('Afghanistan', '/wiki/Geography_of_Afghanistan'),
('Pumari Chhish', '/wiki/Pumari_Chhish'),
('Passu Sar', '/wiki/Passu_Sar'),
('Malubiting', '/wiki/Malubiting'),
('Gangapurna', '/wiki/Annapurna'),
('Annapurna Himalaya', '/wiki/Annapurna'),
('Muchu Chhish (Batura V)', '/w/index.php?title=Muchu_Chhish_(Batura_V)&action=edit&redlink=1'),
('Jengish Chokusu', '/wiki/Jengish_Chokusu'),
('Tian Shan', '/wiki/Tian_Shan'),
('K12', '/w/index.php?title=Sia_(mountain)&action=edit&redlink=1'),
('Sia Kangri', '/wiki/Sia_Kangri'),
('Istor-o-Nal', '/wiki/Istor-o-Nal'),
('Ghent Kangri', '/wiki/Ghent_Kangri'),
('Haramosh Peak', '/wiki/Haramosh_Peak'),
('Kabru', '/wiki/Kabru'),
('Ultar', '/wiki/Ultar'),
('Rimo I', '/wiki/Rimo_I'),
('Sherpi Kangri', '/wiki/Sherpi_Kangri'),
('Labuche Kang', '/wiki/Labuche_Kang'),
('Kirat Chuli', '/wiki/Kirat_Chuli'),
('Skil Brum', '/wiki/Skil_Brum'),
('Gimmigela Chuli', '/wiki/Gimmigela_Chuli'),
('Bojohagur Duanasir', '/wiki/Bojohagur_Duanasir'),
('Chamlang', '/wiki/Chamlang'),
('Jomolhari', '/wiki/Mount_Jomolhari'),
('Bhutan', '/wiki/Geography_of_Bhutan'),
('Baltoro Kangri', '/wiki/Baltoro_Kangri'),
('Siguang Ri', '/wiki/Siguang_Ri'),
('The Crown', '/wiki/The_Crown_(mountain)'),
('Gyala Peri', '/wiki/Gyala_Peri'),
('Porong Ri', '/wiki/Porong_Ri'),
('Baintha Brakk', '/wiki/Baintha_Brakk'),
('Yutmaru Sar', '/wiki/Yutmaru_Sar'),
('K6', '/wiki/K6_(mountain)'),
('Kangpenqing', '/wiki/Kangpenqing'),
('Mana Peak', '/wiki/Kamet'),
('Muztagh Tower', '/wiki/Muztagh_Tower'),
('Diran', '/wiki/Diran'),
('Apsarasas Kangri', '/wiki/Apsarasas_Kangri'),
('Langtang Lirung', '/wiki/Langtang_Lirung'),
('Khartaphu', '/wiki/Khartaphu'),
('Tongshanjiabu', '/wiki/Tongshanjiabu'),
('Langtang Ri', '/wiki/Langtang_Ri'),
('Kangphu Kang', '/wiki/Kangphu_Kang'),
('Annapurna South', '/wiki/Annapurna'),
('Melungtse', '/wiki/Melungtse'),
('Rolwaling', '/wiki/Rolwaling_Himal'),
('Liushi Shan', '/wiki/Liushi_Shan'),
('Baruntse', '/wiki/Baruntse'),
('Pumori', '/wiki/Pumori'),
('Hardeol', '/wiki/Hardeol'),
('Gasherbrum V', '/wiki/Gasherbrum_V'),
('Nemjung', '/wiki/Nemjung'),
('Udren Zom', '/wiki/Udren_Zom'),
('Chaukhamba', '/wiki/Chaukhamba'),
('Nun Kun', '/wiki/Nun_Kun'),
('Tilicho Peak', '/wiki/Tilicho_Peak'),
('Gauri Sankar', '/wiki/Gauri_Sankar'),
('Rolwaling', '/wiki/Rolwaling_Himal'),
('Lenin Peak', '/wiki/Lenin_Peak'),
('Pamir Mountains', '/wiki/Pamir_Mountains'),
('Tajikistan', '/wiki/Geography_of_Tajikistan'),
('Api', '/wiki/Api_(mountain)'),
('Pauhunri', '/wiki/Pauhunri'),
('Trisul', '/wiki/Trisul'),
('Korzhenevskaya', '/wiki/Peak_Korzhenevskaya'),
('Lunpo Gangri', '/wiki/Lunpo_Gangri'),
('Satopanth', '/wiki/Satopanth'),
('Tirsuli', '/wiki/Tirsuli'),
('Dunagiri', '/wiki/Dunagiri_(mountain)'),
('Kangto', '/wiki/Kangto'),
('Nyegyi Kansang', '/wiki/Nyegyi_Kansang'),
('Kezhen Peak', '/wiki/Kezhen_Peak'),
('Shah Dhar', '/wiki/Shah_Dhar'),
('Spantik', '/wiki/Spantik'),
('Khan Tengri', '/wiki/Khan_Tengri'),
('Tian Shan', '/wiki/Tian_Shan'),
('Machapuchare', '/wiki/Machapuchare'),
('Annapurna Himalaya', '/wiki/Annapurna'),
('Laila Peak (Haramosh Valley)', '/wiki/Laila_Peak_(Haramosh_Valley)'),
('Kang Guru', '/wiki/Kang_Guru'),
('Manaslu Himalaya', '/wiki/Manaslu'),
('Karun Kuh', '/wiki/Karun_Kuh'),
('Karakoram', '/wiki/Karakoram'),
('Avicenna Peak', '/wiki/Avicenna_Peak'),
('Pamir Mountains', '/wiki/Pamir_Mountains'),
('Ulugh Muztagh', '/wiki/Ulugh_Muztagh'),
('Kunlun Mountains', '/wiki/Kunlun_Mountains'),
('Aconcagua', '/wiki/Aconcagua'),
('Andes', '/wiki/Andes'),
('Kedarnath (mountain)', '/wiki/Kedarnath_(mountain)'),
('Himalayas', '/wiki/Uttarakhand'),
('K7', '/wiki/K7_(mountain)'),
('Panchchuli', '/wiki/Panchchuli'),
('Himalayas', '/wiki/Uttarakhand'),
('Thalay Sagar', '/wiki/Thalay_Sagar'),
('Himalayas', '/wiki/Uttarakhand'),
('Lunkho e Dosare', '/wiki/Lunkho_e_Dosare'),
('Hindu Kush', '/wiki/Hindu_Kush'),
('Ojos del Salado', '/wiki/Ojos_del_Salado'),
('Andes', '/wiki/Andes'),
('Siniolchu', '/wiki/Siniolchu'),
('Kangchenjunga Himalaya', '/wiki/Kangchenjunga'),
('Kanjiroba', '/wiki/Kanjiroba'),
('Nanda Kot', '/wiki/Nanda_Kot'),
('Himalayas', '/wiki/Geography_of_Uttarakhand'),
('Kubi Gangri', '/wiki/Kubi_Gangri'),
('Angel Sar', '/wiki/Angel_Sar'),
('Jethi Bahurani', '/wiki/Jethi_Bahurani'),
('Chongra Peak', '/wiki/Chongra_Peak'),
('Nanga Parbat Himalaya', '/wiki/Nanga_Parbat'),
('Reo Purgyil', '/wiki/Reo_Purgyil'),
('Western Himalaya', '/wiki/Western_Himalaya'),
('Ama Dablam', '/wiki/Ama_Dablam'),
('Monte Pissis', '/wiki/Monte_Pissis'),
('Biarchedi', '/wiki/Biarchedi'),
('Huascarán Sur', '/wiki/Huascar%C3%A1n'),
('Cerro Bonete', '/wiki/Cerro_Bonete'),
('Nevado Tres Cruces', '/wiki/Nevado_Tres_Cruces'),
('Kawagarbo', '/wiki/Kawagarbo'),
('Llullaillaco', '/wiki/Llullaillaco'),
('Cho Polu', '/wiki/Cho_Polu'),
('Kangju Kangri', '/wiki/Kangju_Kangri'),
('Changla', '/wiki/Changla'),
('Mercedario', '/wiki/Mercedario'),
('Mount Pandim', '/wiki/Mount_Pandim'),
('Num Ri', '/wiki/Num_Ri'),
('Lungser Kangri', '/w/index.php?title=Lungser_Kangri&action=edit&redlink=1'),
('Meru Peak', '/wiki/Meru_Peak'),
('Himalayas', '/wiki/Uttarakhand'),
('Gul Lasht Zom', '/wiki/Gul_Lasht_Zom'),
('Huascarán Norte', '/wiki/Huascar%C3%A1n'),
('Khumbutse', '/wiki/Khumbutse'),
('Mount Kailash', '/wiki/Mount_Kailash'),
('Transhimalaya', '/wiki/Transhimalaya'),
('Yerupajá', '/wiki/Yerupaj%C3%A1'),
('Nevado Tres Cruces Central', '/wiki/Nevado_Tres_Cruces_Central'),
('Thamserku', '/wiki/Thamserku'),
('Geladaindong Peak', '/wiki/Geladaindong_Peak'),
('Incahuasi', '/wiki/Incahuasi'),
('Pangpoche', '/wiki/Pangpoche'),
('Manirang', '/wiki/Manirang'),
('Nilkantha', '/wiki/Nilkantha_(mountain)'),
('Himalayas', '/wiki/Geography_of_Uttarakhand'),
('Phuparash Peak', '/wiki/Phuparash_Peak'),
('Sickle Moon Peak', '/wiki/Sickle_Moon_Peak'),
('Buni Zom', '/wiki/Buni_Zom'),
('Nevado Sajama', '/wiki/Nevado_Sajama'),
('Ghamubar Zom', '/wiki/Ghamubar_Zom'),
('Singu Chuli', '/wiki/Singu_Chuli'),
('Annapurna', '/wiki/Annapurna'),
('Taboche', '/wiki/Taboche'),
('Cerro El Muerto', '/wiki/Cerro_El_Muerto'),
('Mera Peak', '/wiki/Mera_Peak'),
('Hiunchuli', '/wiki/Hiunchuli'),
('Annapurna Himalaya', '/wiki/Annapurna'),
('Cholatse', '/wiki/Cholatse'),
('Illimani', '/wiki/Illimani'),
('Ancohuma', '/wiki/Ancohuma'),
('Coropuna', '/wiki/Coropuna'),
('Antofalla', '/wiki/Antofalla'),
('Kang Yatze', '/wiki/Kang_Yatze'),
('Huandoy', '/wiki/Huandoy'),
('Ausangate', '/wiki/Ausangate'),
('Illampu', '/wiki/Illampu'),
('Kusum Kangguru', '/wiki/Kusum_Kangguru'),
('Kinnaur Kailash', '/wiki/Kinnaur_Kailash'),
('Parinaquta', '/wiki/Parinacota_Volcano'),
('Siula Grande', '/wiki/Siula_Grande'),
('Bamba Dhura', '/wiki/Bamba_Dhura'),
('Himalayas', '/wiki/Geography_of_Uttarakhand'),
('Ampato', '/wiki/Ampato'),
('Amne Machin', '/wiki/Amne_Machin'),
('Pomerape', '/wiki/Pomerape'),
('Salcantay', '/wiki/Salcantay'),
('Chimborazo', '/wiki/Chimborazo_(volcano)'),
('Mount Siguniang', '/wiki/Mount_Siguniang'),
('Grid Nie Mountain', '/wiki/Grid_Nie_Mountain'),
('Yuzhu Peak', '/wiki/Yuzhu_Peak'),
('Genyen Massif', '/wiki/Genyen_Massif'),
('Kongde Ri', '/wiki/Kongde_Ri'),
('Aucanquilcha', '/wiki/Aucanquilcha'),
('Imja Tse', '/wiki/Imja_Tse'),
('Denali', '/wiki/Denali'),
('Alaska Range', '/wiki/Alaska_Range'),
('Stok Kangri', '/wiki/Stok_Kangri'),
('Pisang Peak', '/wiki/Pisang_Peak'),
('Annapurna Himalaya', '/wiki/Annapurna'),
('Huayna Potosí', '/wiki/Huayna_Potos%C3%AD'),
('Aracar', '/wiki/Aracar'),
('Chachakumani', '/wiki/Chachakumani'),
('Chachani', '/wiki/Chachani'),
('Mianzimu', '/wiki/Mianzimu'),
('Acotango', '/wiki/Acotango'),
('Socompa', '/wiki/Socompa'),
('Acamarachi', '/wiki/Acamarachi'),
('Shayaz', '/wiki/Shayaz'),
('Hualca Hualca', '/wiki/Hualca_Hualca'),
('Uturunku', '/wiki/Uturunku'),
('Mitre Peak', '/wiki/Mitre_Peak_(Pakistan)'),
('Laila Peak', '/wiki/Laila_Peak_(Rupal_Valley)'),
('Mount Logan', '/wiki/Mount_Logan'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Yukon', '/wiki/Geography_of_Yukon'),
('Alpamayo', '/wiki/Alpamayo'),
('Andes', '/wiki/Andes'),
('Peru', '/wiki/Geography_of_Peru'),
('Cerro Lípez', '/wiki/Cerro_L%C3%ADpez'),
('Andes', '/wiki/Andes'),
('Bolivia', '/wiki/Geography_of_Bolivia'),
('Licancabur', '/wiki/Licancabur'),
('Andes', '/wiki/Andes'),
('Bolivia', '/wiki/Geography_of_Bolivia'),
('Falak Sar', '/wiki/Falak_Sar_(Swat)'),
('Cotopaxi', '/wiki/Cotopaxi'),
('Andes', '/wiki/Andes'),
('Ecuador', '/wiki/Geography_of_Ecuador'),
('Mount Kilimanjaro', '/wiki/Mount_Kilimanjaro'),
('Tanzania', '/wiki/Geography_of_Tanzania'),
('Hkakabo Razi', '/wiki/Hkakabo_Razi'),
('Himalayas', '/wiki/Himalayas'),
('Myanmar', '/wiki/Geography_of_Myanmar'),
('El Misti', '/wiki/El_Misti'),
('Andes', '/wiki/Andes'),
('Peru', '/wiki/Geography_of_Peru'),
('Altun Shan', '/wiki/Altun_Shan'),
('Altyn-Tagh', '/wiki/Altyn-Tagh'),
('Gansu', '/wiki/Gansu'),
('Cayambe', '/wiki/Cayambe_(volcano)'),
('Andes', '/wiki/Andes'),
('Ecuador', '/wiki/Geography_of_Ecuador'),
('Pico Cristóbal Colón', '/wiki/Pico_Crist%C3%B3bal_Col%C3%B3n'),
('Sierra Nevada de Santa Marta', '/wiki/Sierra_Nevada_de_Santa_Marta'),
('Colombia', '/wiki/Geography_of_Colombia'),
('Antisana', '/wiki/Antisana'),
('Andes', '/wiki/Andes'),
('Ecuador', '/wiki/Geography_of_Ecuador'),
('Nevado Pisco', '/wiki/Nevado_Pisco'),
('Andes', '/wiki/Andes'),
('Peru', '/wiki/Geography_of_Peru'),
('Nevado Anallajsi', '/wiki/Nevado_Anallajsi'),
('Andes', '/wiki/Andes'),
('Bolivia', '/wiki/Geography_of_Bolivia'),
('Pokalde', '/wiki/Pokalde'),
('Khumbu', '/wiki/Khumbu'),
('Nepal', '/wiki/Geography_of_Nepal'),
('Ubinas', '/wiki/Ubinas'),
('Andes', '/wiki/Andes'),
('Peru', '/wiki/Geography_of_Peru'),
('Pichu Pichu', '/wiki/Pichu_Pichu'),
('Andes', '/wiki/Andes'),
('Peru', '/wiki/Geography_of_Peru'),
('Mount Elbrus', '/wiki/Mount_Elbrus'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('North Caucasus', '/wiki/North_Caucasus'),
('Mehrbani Peak', '/wiki/Mehrbani_Peak'),
('Karakoram', '/wiki/Karakoram'),
('Pakistan', '/wiki/Geography_of_Pakistan'),
('Pico de Orizaba', '/wiki/Pico_de_Orizaba'),
('Trans-Mexican Volcanic Belt', '/wiki/Trans-Mexican_Volcanic_Belt'),
('Mexico', '/wiki/Geography_of_Mexico'),
('Mount Damavand', '/wiki/Mount_Damavand'),
('Alborz', '/wiki/Alborz'),
('Iran', '/wiki/Geography_of_Iran'),
('Nevado Mismi', '/wiki/Nevado_Mismi'),
('Andes', '/wiki/Andes'),
('Peru', '/wiki/Geography_of_Peru'),
('Jade Dragon Snow Mountain', '/wiki/Jade_Dragon_Snow_Mountain'),
('Hengduan Mountains', '/wiki/Hengduan_Mountains'),
('Yunnan', '/wiki/Yunnan'),
('Lascar Volcano', '/wiki/Lascar_Volcano'),
('Andes', '/wiki/Andes'),
('Chile', '/wiki/Geography_of_Chile'),
('Mount Xuebaoding', '/wiki/Mount_Xuebaoding'),
('Min Mountains', '/wiki/Min_Mountains'),
('Sichuan', '/wiki/Sichuan'),
('Kala Patthar', '/wiki/Kala_Patthar'),
('Khumbu', '/wiki/Khumbu'),
('Nepal', '/wiki/Geography_of_Nepal'),
('Mount Saint Elias', '/wiki/Mount_Saint_Elias'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Yukon', '/wiki/Geography_of_Yukon'),
('Concord Peak', '/wiki/Concord_Peak'),
('Pamir Mountains', '/wiki/Pamir_Mountains'),
('Afghanistan', '/wiki/Geography_of_Afghanistan'),
('Machoi Peak', '/wiki/Machoi_Peak'),
('Himalaya', '/wiki/Himalaya'),
('El Plomo', '/wiki/El_Plomo'),
('Andes', '/wiki/Andes'),
('Chile', '/wiki/Chile'),
('Bogda Feng', '/wiki/Bogda_Feng'),
('Tien Shan', '/wiki/Tien_Shan'),
('Xinjiang', '/wiki/Xinjiang'),
('Mount Little Xuebaoding', '/wiki/Mount_Little_Xuebaoding'),
('Min Mountains', '/wiki/Min_Mountains'),
('Sichuan', '/wiki/Sichuan'),
('Cerro El Plomo', '/wiki/Cerro_El_Plomo'),
('Andes', '/wiki/Andes'),
('Chile', '/wiki/Geography_of_Chile'),
('Popocatépetl', '/wiki/Popocat%C3%A9petl'),
('Trans-Mexican Volcanic Belt', '/wiki/Trans-Mexican_Volcanic_Belt'),
('Mexico', '/wiki/Geography_of_Mexico'),
('Kolahoi Peak', '/wiki/Kolahoi_Peak'),
('Himalaya', '/wiki/Himalaya'),
('Chacaltaya', '/wiki/Chacaltaya'),
('Andes', '/wiki/Andes'),
('Bolivia', '/wiki/Geography_of_Bolivia'),
('Mount Pomiu', '/wiki/Mount_Pomiu'),
('Qionglai Range', '/wiki/Qionglai_Mountains'),
('Sichuan, China', '/wiki/Sichuan,_China'),
('Ritacuba Blanco', '/wiki/Ritacuba_Blanco'),
('Andes', '/wiki/Andes'),
('Colombia', '/wiki/Geography_of_Colombia'),
('Haba Xueshan', '/wiki/Haba_Xueshan'),
('Himalaya', '/wiki/Himalaya'),
('Yunnan, China', '/wiki/Yunnan,_China'),
('Nevado del Ruiz', '/wiki/Nevado_del_Ruiz'),
('Andes', '/wiki/Andes'),
('Colombia', '/wiki/Geography_of_Colombia'),
('El Altar', '/wiki/El_Altar'),
('Andes', '/wiki/Andes'),
('Ecuador', '/wiki/Geography_of_Ecuador'),
('Mount Foraker', '/wiki/Mount_Foraker'),
('Alaska Range', '/wiki/Alaska_Range'),
('Alaska', '/wiki/Geography_of_Alaska'),
('Mount Haramukh', '/wiki/Mount_Haramukh'),
('Himalaya', '/wiki/Himalaya'),
('Maipo', '/wiki/Maipo_(volcano)'),
('Andes', '/wiki/Andes'),
('Argentina', '/wiki/Geography_of_Argentina'),
('Illiniza', '/wiki/Illiniza'),
('Andes', '/wiki/Andes'),
('Ecuador', '/wiki/Geography_of_Ecuador'),
('Sirbal Peak', '/wiki/Sirbal_Peak'),
('Himalaya', '/wiki/Himalaya'),
('Kashmir Valley', '/wiki/Kashmir_Valley'),
('Sangay', '/wiki/Sangay'),
('Andes', '/wiki/Andes'),
('Ecuador', '/wiki/Geography_of_Ecuador'),
('Iztaccíhuatl', '/wiki/Iztacc%C3%ADhuatl'),
('Trans-Mexican Volcanic Belt', '/wiki/Trans-Mexican_Volcanic_Belt'),
('Mexico', '/wiki/Geography_of_Mexico'),
('Mount Lucania', '/wiki/Mount_Lucania'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Yukon', '/wiki/Geography_of_Yukon'),
('Dykh-Tau', '/wiki/Dykh-Tau'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('North Caucasus', '/wiki/North_Caucasus'),
('Shkhara', '/wiki/Shkhara'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('Georgia', '/wiki/Geography_of_Georgia_(country)'),
('Mount Kenya', '/wiki/Mount_Kenya'),
('Kenya', '/wiki/Geography_of_Kenya'),
('Malika Parbat', '/wiki/Malika_Parbat'),
('Himalaya', '/wiki/Himalaya'),
('Kaghan Valley', '/wiki/Kaghan_Valley'),
('Amarnath Peak', '/wiki/Amarnath_Peak'),
('Himalaya', '/wiki/Himalaya'),
('Kashmir Valley', '/wiki/Kashmir_Valley'),
('King Peak', '/wiki/King_Peak_(Yukon)'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Yukon', '/wiki/Geography_of_Yukon'),
('Boris Yeltsin Peak', '/wiki/Boris_Yeltsin_Peak'),
('Teskey Ala-Too', '/wiki/Teskey_Ala-Too'),
('Kyrgyzstan', '/wiki/Geography_of_Kyrgyzstan'),
('Koshtan-Tau', '/wiki/Koshtan-Tau'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('North Caucasus', '/wiki/North_Caucasus'),
('Mount Ararat', '/wiki/Mount_Ararat'),
('Turkey', '/wiki/Geography_of_Turkey'),
('Mount Stanley', '/wiki/Mount_Stanley'),
('Ruwenzori Mountains', '/wiki/Ruwenzori_Mountains'),
('Democratic Republic of the Congo', '/wiki/Geography_of_the_Democratic_Republic_of_the_Congo'),
('Mount Steele', '/wiki/Mount_Steele'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Yukon', '/wiki/Geography_of_Yukon'),
('Janga', '/wiki/Dzhangi-Tau'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('Georgia', '/wiki/Geography_of_Georgia_(country)'),
('Mount Kazbek', '/wiki/Mount_Kazbek'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('Georgia', '/wiki/Geography_of_Georgia_(country)'),
('Tungurahua', '/wiki/Tungurahua'),
('Andes', '/wiki/Andes'),
('Ecuador', '/wiki/Geography_of_Ecuador'),
('Carihuairazo', '/wiki/Carihuairazo'),
('Andes', '/wiki/Andes'),
('Ecuador', '/wiki/Geography_of_Ecuador'),
('Mount Bona', '/wiki/Mount_Bona'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Alaska', '/wiki/Geography_of_Alaska'),
('Mount Blackburn', '/wiki/Mount_Blackburn'),
('Wrangell Mtns.', '/wiki/Wrangell_Mountains'),
('Pico Bolívar', '/wiki/Pico_Bol%C3%ADvar'),
('Sierra Nevada de Mérida', '/wiki/Sierra_Nevada_de_M%C3%A9rida'),
('Pik Talgar', '/wiki/Pik_Talgar'),
('Tian Shan', '/wiki/Tian_Shan'),
('Gunshar', '/w/index.php?title=Gunshar&action=edit&redlink=1'),
('Indus Kohistan, Pakistan', '/w/index.php?title=Indus_Kohistan,_Pakistan&action=edit&redlink=1'),
('Mount Sanford', '/wiki/Mount_Sanford_(Alaska)'),
('Wrangell Mtns.', '/wiki/Wrangell_Mountains'),
('Pico Humboldt', '/wiki/Pico_Humboldt'),
('Sierra Nevada de Mérida', '/wiki/Sierra_Nevada_de_M%C3%A9rida'),
('Vinson Massif', '/wiki/Vinson_Massif'),
('Sentinel Range', '/wiki/Sentinel_Range'),
('Pico Bonpland', '/wiki/Pico_Bonpland'),
('Sierra Nevada de Mérida', '/wiki/Sierra_Nevada_de_M%C3%A9rida'),
('Puncak Jaya', '/wiki/Puncak_Jaya'),
('Sudirman Range', '/wiki/Sudirman_Range'),
('Pico La Concha', '/wiki/Pico_La_Concha'),
('Sierra Nevada de Mérida', '/wiki/Sierra_Nevada_de_M%C3%A9rida'),
('Gistola', '/wiki/Gistola'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('Shota Rustaveli Peak', '/wiki/Shota_Rustaveli_Peak'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('Tetnuldi', '/wiki/Tetnuldi'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('Mount Tyree', '/wiki/Mount_Tyree'),
('Sentinel Range', '/wiki/Sentinel_Range'),
('Huaynaputina', '/wiki/Huaynaputina'),
('Andes', '/wiki/Andes'),
('Alam Kuh', '/wiki/Alam_Kuh'),
('Alborz', '/wiki/Alborz'),
('Mount Wood', '/wiki/Mount_Wood_(Yukon)'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Mount Vancouver', '/wiki/Mount_Vancouver'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Sabalan', '/wiki/Sabalan'),
('Iran', '/wiki/Geography_of_Iran'),
('Mont Blanc', '/wiki/Mont_Blanc'),
('Corazón', '/wiki/Coraz%C3%B3n_(volcano)'),
('Andes', '/wiki/Andes'),
('Pichincha', '/wiki/Pichincha_(volcano)'),
('Andes', '/wiki/Andes'),
('Jimara', '/wiki/Mount_Jimara'),
('Khokh Range', '/wiki/Khokh_Range'),
('Mount Churchill', '/wiki/Mount_Churchill'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Puncak Mandala', '/wiki/Puncak_Mandala'),
('Klyuchevskaya Sopka', '/wiki/Klyuchevskaya_Sopka'),
('Kamchatka', '/wiki/Kamchatka_Peninsula'),
('Puncak Trikora', '/wiki/Puncak_Trikora'),
('Mont Blanc de Courmayeur', '/wiki/Mont_Blanc_de_Courmayeur'),
('Sunset Peak', '/wiki/Sunset_Peak_(Jammu_and_Kashmir)'),
('Mount Slaggard', '/wiki/Mount_Slaggard'),
('Pico Piedras Blancas', '/wiki/Pico_Piedras_Blancas'),
('Pico El Toro', '/wiki/Pico_El_Toro'),
('Andes', '/wiki/Andes'),
('Tatakooti Peak', '/wiki/Tatakooti_Peak'),
('Rumiñahui', '/wiki/Rumi%C3%B1ahui_(volcano)'),
('Andes', '/wiki/Andes'),
('Pico El Leon', '/wiki/Pico_El_Leon'),
('Andes', '/wiki/Andes'),
('Ushba', '/wiki/Ushba'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('Volcán Domuyo', '/wiki/Domuyo'),
('Andes', '/wiki/Andes'),
('Pico Los Nevados', '/w/index.php?title=Pico_Los_Nevados&action=edit&redlink=1'),
('Andes', '/wiki/Andes'),
('Pico Pan de Azucar', '/wiki/Pico_Pan_de_Azucar'),
('Naltar Peak', '/wiki/Naltar_Peak'),
('Pakistan', '/wiki/Geography_of_Pakistan'),
('Mount Fairweather', '/wiki/Mount_Fairweather'),
('Pico Mucuñuque', '/wiki/Pico_Mucu%C3%B1uque'),
('Andes', '/wiki/Andes'),
('Pico El Buitre', '/w/index.php?title=Pico_El_Buitre&action=edit&redlink=1'),
('Andes', '/wiki/Andes'),
('Khazret Sultan', '/wiki/Khazret_Sultan'),
('Gissar', '/wiki/Gissar'),
('Sierra Negra', '/wiki/Sierra_Negra'),
('Mexico', '/wiki/Geography_of_Mexico'),
('Dufourspitze', '/wiki/Dufourspitze'),
('Dunantspitze', '/wiki/Dunantspitze'),
('Nordend', '/wiki/Nordend'),
('Mount Hubbard', '/wiki/Mount_Hubbard'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Nevado de Toluca', '/wiki/Nevado_de_Toluca'),
('Mexico', '/wiki/Geography_of_Mexico'),
('Mount Meru', '/wiki/Mount_Meru_(Tanzania)'),
('Tanzania', '/wiki/Geography_of_Tanzania'),
('Zumsteinspitze', '/wiki/Zumsteinspitze'),
('Signalkuppe', '/wiki/Signalkuppe'),
('Dom', '/wiki/Dom_(Mischabel)'),
('Ras Dashen', '/wiki/Ras_Dashen'),
('Ethiopia', '/wiki/Geography_of_Ethiopia'),
('Mount Bear', '/wiki/Mount_Bear'),
('Mount Wilhelm', '/wiki/Mount_Wilhelm'),
('Papua New Guinea', '/wiki/Geography_of_Papua_New_Guinea'),
('Mount Karisimbi', '/wiki/Mount_Karisimbi'),
('Mount Walsh', '/wiki/Mount_Walsh'),
('Belukha Mountain', '/wiki/Belukha_Mountain'),
('Weisshorn', '/wiki/Weisshorn'),
('Tebulosmta', '/wiki/Tebulosmta'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('Täschhorn', '/wiki/T%C3%A4schhorn'),
('Bazarduzu Dagi', '/wiki/Bazarduzu_Dagi'),
('Azerbaijan', '/wiki/Geography_of_Azerbaijan'),
('Matterhorn', '/wiki/Matterhorn'),
('Mount Rutford', '/wiki/Mount_Rutford'),
('Sentinel Range', '/wiki/Sentinel_Range'),
('Mont Maudit', '/wiki/Mont_Maudit'),
('Babis Mta', '/wiki/Babis_Mta'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('Mount Shani', '/wiki/Mount_Shani'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('Dena', '/wiki/Dena'),
('Zagros Mountains', '/wiki/Zagros_Mountains'),
('Vladimir Putin Peak', '/wiki/Vladimir_Putin_Peak'),
('Kyrgyz Alatau', '/wiki/Kyrgyz_Alatau'),
('Mount Hunter', '/wiki/Mount_Hunter_(Alaska)'),
('Alaska Range', '/wiki/Alaska_Range'),
('Parrotspitze', '/wiki/Parrotspitze'),
('Mount Whitney', '/wiki/Mount_Whitney'),
('Sierra Nevada', '/wiki/Sierra_Nevada_(U.S.)'),
('Mount Alverstone', '/wiki/Mount_Alverstone'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('University Peak', '/wiki/University_Peak_(Alaska)'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Aello Peak', '/wiki/Aello_Peak'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Mount Elbert', '/wiki/Mount_Elbert'),
('Mount Massive', '/wiki/Mount_Massive'),
('Mount Harvard', '/wiki/Mount_Harvard'),
('Mount Rainier', '/wiki/Mount_Rainier'),
('Kholeno', '/wiki/Kholeno'),
('Alborz', '/wiki/Alborz'),
('Mount Williamson', '/wiki/Mount_Williamson'),
('Tavan Bogd Uul', '/wiki/Tavan_Bogd_Uul'),
('Bayan-Ölgii Province', '/wiki/Bayan-%C3%96lgii_Province'),
('Blanca Peak', '/wiki/Blanca_Peak'),
('Rocky Mountains', '/wiki/Rocky_Mountains'),
('La Plata Peak', '/wiki/La_Plata_Peak'),
('Mount Giluwe', '/wiki/Mount_Giluwe'),
('Burchula', '/wiki/Burchula'),
('Uncompahgre Peak', '/wiki/Uncompahgre_Peak'),
('Dent Blanche', '/wiki/Dent_Blanche'),
('Crestone Peak', '/wiki/Crestone_Peak'),
('Mount Lincoln', '/wiki/Mount_Lincoln_(Colorado)'),
('Azad Kuh', '/wiki/Azad_Kuh'),
('Alborz', '/wiki/Alborz'),
('Grays Peak', '/wiki/Grays_Peak'),
('Mount Evans', '/wiki/Mount_Evans'),
('Quandary Peak', '/wiki/Quandary_Peak'),
('Lalveri', '/wiki/Lalveri'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('Mount Antero', '/wiki/Mount_Antero'),
('Torreys Peak', '/wiki/Torreys_Peak'),
('Castle Peak', '/wiki/Castle_Peak_(Colorado)'),
('Longs Peak', '/wiki/Longs_Peak'),
('McArthur Peak', '/wiki/McArthur_Peak'),
('Mount Wilsion', '/wiki/Mount_Wilson_(Colorado)'),
('White Mountain Peak', '/wiki/White_Mountain_Peak'),
('North Palisade', '/wiki/North_Palisade'),
('Ludwigshöhe', '/wiki/Ludwigsh%C3%B6he'),
('Mount Shavano', '/wiki/Mount_Shavano'),
('Colima', '/wiki/Colima_(volcano)'),
('Crestone Needle', '/wiki/Crestone_Needle'),
('Mount Belford', '/wiki/Mount_Belford'),
('Mount Princeton', '/wiki/Mount_Princeton'),
('Mount Shasta', '/wiki/Mount_Shasta'),
('California', '/wiki/Geography_of_California'),
('Mount Elgon', '/wiki/Mount_Elgon'),
('Mount Bross', '/wiki/Mount_Bross'),
('Kit Carson Mountain', '/wiki/Kit_Carson_Mountain'),
('Mount Wrangell', '/wiki/Mount_Wrangell'),
('Maroon Peak', '/wiki/Maroon_Peak'),
('Tabeguache Peak', '/wiki/Tabeguache_Peak'),
('El Diente Peak', '/wiki/El_Diente_Peak'),
('Mount Sill', '/wiki/Mount_Sill'),
('Grand Combin', '/wiki/Grand_Combin'),
('Mount Oxford (Colorado)', '/wiki/Mount_Oxford_(Colorado)'),
('Mount Sneffels', '/wiki/Mount_Sneffels'),
('Mount Democrat', '/wiki/Mount_Democrat'),
('Capitol Peak', '/wiki/Capitol_Peak_(Colorado)'),
('Pikes Peak', '/wiki/Pikes_Peak'),
('Colorado', '/wiki/Geography_of_Colorado'),
('Snowmass Mountain', '/wiki/Snowmass_Mountain'),
('Lenzspitze', '/wiki/Lenzspitze'),
('Mount Russell', '/wiki/Mount_Russell_(California)'),
('Mount Eolus', '/wiki/Mount_Eolus'),
('Windom Peak', '/wiki/Windom_Peak'),
('Challenger Point', '/wiki/Challenger_Point'),
('Mount Columbia', '/wiki/Mount_Columbia_(Colorado)'),
('Mount Adishi', '/wiki/Mount_Adishi'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('Mount Augusta', '/wiki/Mount_Augusta'),
('Saint Elias Mountains', '/wiki/Saint_Elias_Mountains'),
('Humboldt Peak (Colorado)', '/wiki/Humboldt_Peak_(Colorado)'),
('Split Mountain', '/wiki/Split_Mountain_(California)'),
('Mount Bierstadt', '/wiki/Mount_Bierstadt'),
('Diklosmta', '/wiki/Diklosmta'),
('Sunlight Peak', '/wiki/Sunlight_Peak'),
('Mount Sidley', '/wiki/Mount_Sidley'),
('Missouri Mountain', '/wiki/Missouri_Mountain'),
('Culebra Peak', '/wiki/Culebra_Peak'),
('Colorado', '/wiki/Geography_of_Colorado'),
('Handies Peak', '/wiki/Handies_Peak'),
('Ellingwood Point', '/wiki/Ellingwood_Point'),
('Mount Lindsey', '/wiki/Mount_Lindsey'),
('Little Bear Peak', '/wiki/Little_Bear_Peak'),
('Mount Sherman', '/wiki/Mount_Sherman'),
('Redcloud Peak', '/wiki/Redcloud_Peak'),
('Galeras', '/wiki/Galeras'),
('Andes', '/wiki/Andes'),
('Mount Langley', '/wiki/Mount_Langley'),
('Finsteraarhorn', '/wiki/Finsteraarhorn'),
('Pyramid Peak', '/wiki/Pyramid_Peak_(Colorado)'),
('Mount Tyndall', '/wiki/Mount_Tyndall'),
('Wilson Peak', '/wiki/Wilson_Peak'),
('Mount Muir', '/wiki/Mount_Muir'),
('San Luis Peak', '/wiki/San_Luis_Peak'),
('Wetterhorn Peak', '/wiki/Wetterhorn_Peak'),
('Middle Palisade', '/wiki/Middle_Palisade'),
('Huron Peak', '/wiki/Huron_Peak'),
('Mount of the Holy Cross', '/wiki/Mount_of_the_Holy_Cross'),
('Thunderbolt Peak', '/wiki/Thunderbolt_Peak'),
('Sunshine Peak', '/wiki/Sunshine_Peak'),
('Mount Strickland', '/wiki/Mount_Strickland'),
('Pigeon Peak', '/wiki/Pigeon_Peak'),
('Mount Kennedy', '/wiki/Mount_Kennedy'),
('Pointe Bayeux', '/wiki/Pointe_Bayeux'),
('Graian Alps', '/wiki/Graian_Alps'),
('Mont Blanc du Tacul', '/wiki/Mont_Blanc_du_Tacul'),
('Graian Alps', '/wiki/Graian_Alps'),
('Stecknadelhorn', '/wiki/Stecknadelhorn'),
('Avalanche Peak', '/wiki/Avalanche_Peak_(Yukon)'),
('Castor', '/wiki/Castor_(mountain)'),
('Zinalrothorn', '/wiki/Zinalrothorn'),
('Volcán Tajumulco', '/wiki/Volc%C3%A1n_Tajumulco'),
('Guatemala', '/wiki/Geography_of_Guatemala'),
('Hohberghorn', '/wiki/Hohberghorn'),
('Turret Peak', '/wiki/Turret_Peak_(Colorado)'),
('Mount Darwin', '/wiki/Mount_Darwin_(California)'),
('Mount Hayes', '/wiki/Mount_Hayes'),
('Alaska', '/wiki/Geography_of_Alaska'),
('Sacabaya', '/wiki/Sacabaya'),
('Bolivia', '/wiki/Geography_of_Bolivia'),
('Grandes Jorasses', '/wiki/Grandes_Jorasses'),
('Gannett Peak', '/wiki/Gannett_Peak'),
('Mauna Kea', '/wiki/Mauna_Kea'),
('Hawaii', '/wiki/Geography_of_Hawaii'),
('Alphubel', '/wiki/Alphubel'),
('Mauna Kea', '/wiki/Mauna_Kea'),
('Hawaii, USA', '/wiki/Hawaii,_USA'),
('Cofre de Perote', '/wiki/Cofre_de_Perote'),
('Mexico', '/wiki/Geography_of_Mexico'),
('Zard-Kuh', '/wiki/Zard-Kuh'),
('Zagros Mountains', '/wiki/Zagros_Mountains'),
('Shah Alborz', '/wiki/Shah_Alborz'),
('Alborz', '/wiki/Alborz'),
('Rimpfischhorn', '/wiki/Rimpfischhorn'),
('Grand Teton', '/wiki/Grand_Teton'),
('Mount Cook', '/wiki/Mount_Cook_(Saint_Elias_Mountains)'),
('Aletschhorn', '/wiki/Aletschhorn'),
('Strahlhorn', '/wiki/Strahlhorn'),
('Fremont Peak', '/wiki/Fremont_Peak_(Wyoming)'),
('Mount Warren', '/wiki/Mount_Warren'),
('Mount Sidley', '/wiki/Mount_Sidley'),
('Antarctica', '/wiki/Geography_of_Antarctica'),
("Dent d'Hérens", '/wiki/Dent_d%27H%C3%A9rens'),
('Mauna Loa', '/wiki/Mauna_Loa'),
('Hawaii', '/wiki/Geography_of_Hawaii'),
('Jbel Toubkal', '/wiki/Jbel_Toubkal'),
('Mount Minto', '/wiki/Mount_Minto_(Antarctica)'),
('Antarctica', '/wiki/Geography_of_Antarctica'),
('Breithorn', '/wiki/Breithorn'),
('Jungfrau', '/wiki/Jungfrau'),
('Bishorn', '/wiki/Bishorn'),
('Mount Helen', '/wiki/Mount_Helen_(Wyoming)'),
('El Mela', '/wiki/El_Mela'),
('Andes', '/wiki/Andes'),
('Mount Quincy Adams', '/wiki/Mount_Quincy_Adams_(Fairweather_Range)'),
('Doublet Peak', '/wiki/Doublet_Peak'),
('Turret Peak', '/wiki/Turret_Peak_(Wyoming)'),
('Mount Parnassus (Colorado)', '/wiki/Mount_Parnassus_(Colorado)'),
('Uludoruk (Reşko / Gelyaşin)', '/w/index.php?title=Uludoruk_(Re%C5%9Fko_/_Gelya%C5%9Fin)&action=edit&redlink=1'),
('Mount Sacagawea', '/wiki/Mount_Sacagawea'),
('Mount Dubois', '/wiki/Mount_Dubois'),
('Mount Muhabura (Albertine Rift)', '/w/index.php?title=Mount_Muhabura_(Albertine_Rift)&action=edit&redlink=1'),
('Kings Peak', '/wiki/Kings_Peak_(Utah)'),
('Aiguille Verte', '/wiki/Aiguille_Verte'),
('Mount Bangeta', '/wiki/Mount_Bangeta'),
('Mount Dickerson', '/wiki/Mount_Dickerson'),
('Queen Alexandra Range', '/wiki/Queen_Alexandra_Range'),
('Monte Tlaloc', '/w/index.php?title=Monte_Tlaloc&action=edit&redlink=1'),
('Mexican Volcanic Belt', '/w/index.php?title=Mexican_Volcanic_Belt&action=edit&redlink=1'),
('Jackson Peak', '/wiki/Jackson_Peak_(Fremont_County,_Wyoming)'),
('Mount Woodrow Wilson', '/wiki/Mount_Woodrow_Wilson'),
('Aiguilles du Diable', '/wiki/Aiguilles_du_Diable'),
('Graian Alps', '/wiki/Graian_Alps'),
('Bastion Peak', '/wiki/Bastion_Peak'),
('Aiguille Blanche de Peuterey', '/wiki/Aiguille_Blanche_de_Peuterey'),
('Mönch', '/wiki/M%C3%B6nch'),
('Mount Febbas', '/wiki/Mount_Febbas'),
('Barre des Écrins', '/wiki/Barre_des_%C3%89crins'),
('Dauphiné Alps', '/wiki/Dauphin%C3%A9_Alps'),
('Mount Aragats', '/wiki/Mount_Aragats'),
('Armenia', '/wiki/Geography_of_Armenia'),
('Mount Cameroon', '/wiki/Mount_Cameroon'),
('Cameroon', '/wiki/Geography_of_Cameroon'),
('Mount Kinabalu', '/wiki/Mount_Kinabalu'),
('Grizzly Peak D', '/wiki/Grizzly_Peak_(Summit_County,_Colorado)'),
('Pollux', '/wiki/Pollux_(mountain)'),
('Kīlauea', '/wiki/K%C4%ABlauea'),
('Hawaii', '/wiki/Geography_of_Hawaii'),
('Mount Wade', '/wiki/Mount_Wade'),
('Mount Victoria', '/wiki/Mount_Victoria,_Papua_New_Guinea'),
('Centennial Peak', '/wiki/Centennial_Peak_(Antarctica)'),
('Gran Paradiso', '/wiki/Gran_Paradiso'),
('Ober Gabelhorn', '/wiki/Ober_Gabelhorn'),
('Piz Bernina', '/wiki/Piz_Bernina'),
('Fiescherhorn', '/wiki/Fiescherhorn'),
('Grünhorn', '/wiki/Gr%C3%BCnhorn'),
('Lauteraarhorn', '/wiki/Lauteraarhorn'),
('Aiguille du Géant', '/wiki/Aiguille_du_G%C3%A9ant'),
('Graian Alps', '/wiki/Graian_Alps'),
('Mount Sniktau', '/wiki/Mount_Sniktau'),
('Allalinhorn', '/wiki/Allalinhorn'),
('Wind River Peak', '/wiki/Wind_River_Peak'),
('Latsga', '/wiki/Latsga'),
('Caucasus Mountains', '/wiki/Caucasus_Mountains'),
('Weissmies', '/wiki/Weissmies'),
('Mount Waddington', '/wiki/Mount_Waddington'),
('Mount Marcus Baker', '/wiki/Mount_Marcus_Baker'),
('Dôme de neige des Écrins', '/w/index.php?title=D%C3%B4me_de_neige_des_%C3%89crins&action=edit&redlink=1'),
('Dauphiné Alps', '/wiki/Dauphin%C3%A9_Alps'),
('Conejos Peak', '/wiki/Conejos_Peak'),
('Dent du Géant', '/wiki/Dent_du_G%C3%A9ant'),
('Red Slate Mountain', '/wiki/Red_Slate_Mountain'),
('Cloud Peak', '/wiki/Cloud_Peak'),
('Wheeler Peak', '/wiki/Wheeler_Peak_(New_Mexico)'),
('Lagginhorn', '/wiki/Lagginhorn'),
('Twilight Peak', '/wiki/Twilight_Peak'),
('Francs Peak', '/wiki/Francs_Peak'),
('Mount Walter', '/wiki/Mount_Walter_(New_Mexico)'),
('Les Droites', '/wiki/Les_Droites'),
('Piz Zupò', '/wiki/Piz_Zup%C3%B2'),
('Bernina Range', '/wiki/Bernina_Range'),
('Truchas Peak', '/wiki/Truchas_Peak'),
('Sangre de Cristo Mountains', '/wiki/Sangre_de_Cristo_Mountains'),
('Fletschhorn', '/wiki/Fletschhorn'),
('Pennine Alps', '/wiki/Pennine_Alps'),
('Mount Albert Edward', '/wiki/Mount_Albert_Edward,_Papua_New_Guinea'),
('Papua New Guinea', '/wiki/Papua_New_Guinea'),
('La Meije', '/wiki/Meije'),
('Dauphiné Alps', '/wiki/Dauphin%C3%A9_Alps'),
('Wheeler Peak', '/wiki/Wheeler_Peak_(Nevada)'),
('Snake Range', '/wiki/Snake_Range'),
('Mount Dana', '/wiki/Mount_Dana'),
('California', '/wiki/California'),
('Acatenango', '/wiki/Acatenango'),
('Guatemala', '/wiki/Guatemala'),
('Piz Roseg', '/wiki/Piz_Roseg'),
('Bernina Range', '/wiki/Bernina_Range'),
('Piz Scerscen', '/wiki/Piz_Scerscen'),
('Bernina Range', '/wiki/Bernina_Range'),
('Eiger', '/wiki/Eiger'),
('Bernese Oberland', '/wiki/Bernese_Oberland'),
('Mount Tochal', '/wiki/Tochal'),
('Alborz', '/wiki/Alborz'),
('Black Tooth Mountain', '/wiki/Black_Tooth_Mountain'),
('Bighorn Mountains', '/wiki/Bighorn_Mountains'),
('Grand Cornier', '/wiki/Grand_Cornier'),
('Pennine Alps', '/wiki/Pennine_Alps'),
('Mount Owen', '/wiki/Mount_Owen_(Wyoming)'),
('Teton Range', '/wiki/Teton_Range'),
('Ailefroide', '/wiki/Ailefroide'),
('Dauphiné Alps', '/wiki/Dauphin%C3%A9_Alps'),
('Mount Robson', '/wiki/Mount_Robson'),
('Descabezado Grande', '/wiki/Descabezado_Grande'),
('Chile', '/wiki/Chile'),
('Yu Shan (Mount Jade)', '/wiki/Yu_Shan'),
('Mont Pelvoux', '/wiki/Mont_Pelvoux'),
('Dauphiné Alps', '/wiki/Dauphin%C3%A9_Alps'),
('Mount Julian', '/wiki/Mount_Julian_(Colorado)'),
('Colorado', '/wiki/Geography_of_Colorado'),
('Ajusco', '/wiki/Ajusco'),
('Mount Erciyes', '/wiki/Mount_Erciyes'),
('Central Anatolia', '/wiki/Central_Anatolia'),
('Bomber Mountain', '/wiki/Bomber_Mountain'),
('Bighorn Range', '/wiki/Bighorn_Range'),
('Pic Sans Nom', '/wiki/Pic_Sans_Nom'),
('Dauphiné Alps', '/wiki/Dauphin%C3%A9_Alps'),
('Jicarita Peak', '/w/index.php?title=Jicarita_Peak&action=edit&redlink=1'),
('Sangre de Cristo Mountains', '/wiki/Sangre_de_Cristo_Mountains'),
('Ortler', '/wiki/Ortler'),
('Piz Palü', '/wiki/Piz_Pal%C3%BC'),
('Middle Teton', '/wiki/Middle_Teton'),
("Aiguille d'Argentière", '/wiki/Aiguille_d%27Argenti%C3%A8re'),
('Granite Peak', '/wiki/Granite_Peak_(Montana)'),
('Mount Gibbs', '/wiki/Mount_Gibbs'),
('Mount Crillon', '/wiki/Mount_Crillon'),
('Mont Blanc de Cheilon', '/wiki/Mont_Blanc_de_Cheilon'),
('Aiguille du Goûter', '/wiki/Aiguille_du_Go%C3%BBter'),
('Graian Alps', '/wiki/Graian_Alps'),
('Borah Peak', '/wiki/Borah_Peak'),
('Grande Casse', '/wiki/Grande_Casse'),
('Vanoise Massif', '/wiki/Vanoise_Massif'),
('Humphreys Peak', '/wiki/Humphreys_Peak'),
('Santa Fe Baldy', '/wiki/Santa_Fe_Baldy'),
('Aiguille du Midi', '/wiki/Aiguille_du_Midi'),
('Graian Alps', '/wiki/Graian_Alps'),
('Mount Moran', '/wiki/Mount_Moran'),
('Monte Viso', '/wiki/Monte_Viso'),
('Mount Saramati', '/wiki/Mount_Saramati'),
('Nesthorn', '/wiki/Nesthorn'),
('Cerro Chirripó', '/wiki/Cerro_Chirrip%C3%B3'),
('Aiguille des Glaciers', '/wiki/Aiguille_des_Glaciers'),
('South Teton', '/wiki/South_Teton'),
('La Râteau', '/w/index.php?title=La_R%C3%A2teau&action=edit&redlink=1'),
('Dauphiné Alps', '/wiki/Dauphin%C3%A9_Alps'),
('Mount Kerinci', '/wiki/Mount_Kerinci'),
('Großglockner', '/wiki/Gro%C3%9Fglockner'),
("Pigne d'Arolla", '/wiki/Pigne_d%27Arolla'),
('Mount Erebus', '/wiki/Mount_Erebus'),
('Mont Pourri', '/wiki/Mont_Pourri'),
('Vanoise Massif', '/wiki/Vanoise_Massif'),
('Mount Fuji', '/wiki/Mount_Fuji'),
('Wildspitze', '/wiki/Wildspitze'),
('Greenhorn Mountain', '/wiki/Greenhorn_Mountain'),
('Volcán de Fuego', '/wiki/Volc%C3%A1n_de_Fuego'),
('Teewinot Mountain', '/wiki/Teewinot_Mountain'),
('Aiguille du Dru', '/wiki/Aiguille_du_Dru'),
('Graian Alps', '/wiki/Graian_Alps'),
('Aoraki/Mount Cook', '/wiki/Aoraki/Mount_Cook'),
('Pointe de Charbonnel', '/wiki/Pointe_de_Charbonnel'),
('Graian Alps', '/wiki/Graian_Alps'),
('Piz Morteratsch', '/wiki/Piz_Morteratsch'),
('Mount Davis', '/wiki/Mount_Davis_(California)'),
('Mount Morrison', '/wiki/Mount_Morrison_(California)'),
('Mount Taibai', '/wiki/Mount_Taibai'),
('Qin Mountains', '/wiki/Qin_Mountains'),
('Aiguille de la Grande Sassière', '/wiki/Aiguille_de_la_Grande_Sassi%C3%A8re'),
('Graian Alps', '/wiki/Graian_Alps'),
('Lanín', '/wiki/Lan%C3%ADn'),
('Andes', '/wiki/Andes'),
('Mount Adams', '/wiki/Mount_Adams_(Washington)'),
('Cascade Range', '/wiki/Cascade_Range'),
('Mount Columbia', '/wiki/Mount_Columbia_(Canada)'),
('Mount Adams', '/wiki/Mount_Adams_(Washington)'),
('Teepe Pillar', '/wiki/Teepe_Pillar'),
('Weißkugel', '/wiki/Wei%C3%9Fkugel'),
('Minarets', '/wiki/Minarets_(California)'),
('Mount Huntington', '/wiki/Mount_Huntington_(Alaska)'),
('Bedori Peak', '/w/index.php?title=Bedori_Peak&action=edit&redlink=1'),
('Mount Rinjani', '/wiki/Mount_Rinjani'),
('Cerro del Potosí', '/wiki/Cerro_del_Potos%C3%AD'),
('Teide', '/wiki/Teide'),
('Asperity Mountain', '/wiki/Asperity_Mountain'),
('Sahand', '/wiki/Sahand'),
('Monte San Lorenzo', '/wiki/Monte_San_Lorenzo'),
('Wetterhorn', '/wiki/Wetterhorn'),
('Dent Parrachée', '/wiki/Dent_Parrach%C3%A9e'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Gunnbjørn', '/wiki/Gunnbj%C3%B8rn'),
('North Twin Peak', '/wiki/North_Twin_Peak'),
('Monte Disgrazia', '/wiki/Monte_Disgrazia'),
('Semeru', '/wiki/Semeru'),
('Les Bans', '/wiki/Les_Bans'),
('Cloudveil Dome', '/wiki/Cloudveil_Dome'),
('Thor Peak', '/wiki/Thor_Peak_(Wyoming)'),
('Medicine Bow Peak', '/wiki/Medicine_Bow_Peak'),
('Hyndman Peak', '/wiki/Hyndman_Peak'),
('Mount Clemenceau', '/wiki/Mount_Clemenceau'),
('Mount Frakes', '/wiki/Mount_Frakes'),
('Grande Motte', '/wiki/Grande_Motte'),
('Vanoise Massif', '/wiki/Vanoise_Massif'),
('Sierra Blanca', '/wiki/Sierra_Blanca_(New_Mexico)'),
('Sacramento Mountains', '/wiki/Sacramento_Mountains'),
('Pointe de la Fournache', '/wiki/Pointe_de_la_Fournache'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Buck Mountain', '/wiki/Buck_Mountain_(Wyoming)'),
('Mount Nebo', '/wiki/Mount_Nebo_(Utah)'),
('Mount Charleston', '/wiki/Mount_Charleston'),
('Hintere Schwärze', '/wiki/Hintere_Schw%C3%A4rze'),
('Nez Perce Peak', '/wiki/Nez_Perce_Peak'),
('Mount Alberta', '/wiki/Mount_Alberta'),
('Mount Assiniboine', '/wiki/Mount_Assiniboine'),
('Tödi', '/wiki/T%C3%B6di'),
('Mount Forbes', '/wiki/Mount_Forbes'),
('Lautaro', '/wiki/Lautaro_(volcano)'),
('Dôme de la Sache', '/wiki/D%C3%B4me_de_la_Sache'),
('Castle Peak', '/wiki/Castle_Peak_(Idaho)'),
("Dôme de l'Arpont", '/wiki/D%C3%B4me_de_l%27Arpont'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Dôme de Chasseforêt', '/wiki/D%C3%B4me_de_Chassefor%C3%AAt'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Makra Peak', '/wiki/Makra_Peak'),
('Sierra Velluda', '/wiki/Sierra_Velluda'),
('Grand Roc Noir', '/wiki/Grand_Roc_Noir'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Mount Timpanogos', '/wiki/Mount_Timpanogos'),
('Dôme des Nants', '/wiki/D%C3%B4me_des_Nants'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Ryan Peak', '/wiki/Ryan_Peak_(Idaho)'),
('South Twin Peak', '/wiki/South_Twin_Peak'),
('Olan', '/wiki/Olan_(mountain)'),
('Aiguille de Péclet', '/wiki/Aiguille_de_P%C3%A9clet'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Presanella', '/wiki/Presanella'),
('Mount Steere', '/wiki/Mount_Steere'),
('Monarch Mountain', '/wiki/Monarch_Mountain'),
('Monte Leone', '/wiki/Monte_Leone'),
('Mont Turia', '/wiki/Mont_Turia'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Mount Temple', '/wiki/Mount_Temple_(Alberta)'),
('Disappointment Peak', '/wiki/Disappointment_Peak_(Wyoming)'),
('Mount Woodring', '/wiki/Mount_Woodring'),
('Aiguille de Polset', '/wiki/Aiguille_de_Polset'),
('Vanoise Massif', '/wiki/Vanoise_Massif'),
('Snow Dome', '/wiki/Snow_Dome_(Canada)'),
("Aiguilles d'Arves", '/wiki/Aiguilles_d%27Arves'),
('Arve Massif', '/w/index.php?title=Arve_Massif&action=edit&redlink=1'),
('Mont de Gébroulaz', '/wiki/Mont_de_G%C3%A9broulaz'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Mount San Gorgonio', '/wiki/Mount_San_Gorgonio'),
('Mount Kitchener', '/wiki/Mount_Kitchener'),
('Zuckerhütl', '/wiki/Zuckerh%C3%BCtl'),
('Mount Wister', '/wiki/Mount_Wister'),
('Mount Saskatchewan', '/wiki/Mount_Saskatchewan_(Yukon)'),
('Mount Tasman', '/wiki/Mount_Tasman'),
('Mount Hungabee', '/wiki/Mount_Hungabee'),
('Mount Athabasca', '/wiki/Mount_Athabasca'),
('Tronador', '/wiki/Tronador'),
('Mount Saint John', '/wiki/Mount_Saint_John'),
('Thabana Ntlenyana', '/wiki/Thabana_Ntlenyana'),
('Pointes du Châtelard', '/wiki/Pointes_du_Ch%C3%A2telard'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Mulhacén', '/wiki/Mulhac%C3%A9n'),
('Mount Berlin', '/wiki/Mount_Berlin'),
('Volcán Barú', '/wiki/Volc%C3%A1n_Bar%C3%BA'),
('Koh-i-Takatu Sraghurgai', '/w/index.php?title=Koh-i-Takatu_Sraghurgai&action=edit&redlink=1'),
('Roc des Saints Pères', '/wiki/Roc_des_Saints_P%C3%A8res'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Mount Brazeau', '/wiki/Mount_Brazeau'),
('Mount Nyiragongo', '/wiki/Mount_Nyiragongo'),
('Ruby Dome', '/wiki/Ruby_Dome'),
('Roche de la Muzelle', '/wiki/Roche_de_la_Muzelle'),
('Dauphine Alps', '/wiki/Dauphine_Alps'),
('Mount Victoria', '/wiki/Mount_Victoria_(Bow_Range)'),
('Abajo Peak', '/wiki/Abajo_Peak'),
('Eagle Peak', '/wiki/Eagle_Peak_(Wyoming)'),
('Doane Peak', '/wiki/Doane_Peak'),
('Ranger Peak', '/wiki/Ranger_Peak_(Wyoming)'),
('Cerro de la Muerte', '/wiki/Cerro_de_la_Muerte'),
('Furgghorn', '/wiki/Furgghorn'),
('Mafadi', '/wiki/Mafadi'),
('Mount Andromeda', '/wiki/Mount_Andromeda_(Alberta)'),
('Mount Joffre', '/wiki/Mount_Joffre'),
('Hilgard Peak', '/wiki/Hilgard_Peak,_Montana'),
('Static Peak', '/wiki/Static_Peak'),
('Pointe de la Sana', '/wiki/Pointe_de_la_Sana'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Eagles Rest Peak', '/wiki/Eagles_Rest_Peak'),
('Irazú Volcano', '/wiki/Iraz%C3%BA_Volcano'),
('Mount Hood', '/wiki/Mount_Hood'),
('Deltaform Mountain', '/wiki/Deltaform_Mountain'),
('Mount Lefroy', '/wiki/Mount_Lefroy'),
("Pointe de l'Échelle", '/wiki/Pointe_de_l%27%C3%89chelle'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Pointe du Bouchet', '/wiki/Pointe_du_Bouchet'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Mount Fitzgerald', '/wiki/Mount_Fitzgerald_(Nevada)'),
('Bellecôte', '/wiki/Bellec%C3%B4te'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Crazy Peak', '/wiki/Crazy_Peak'),
('Emi Koussi', '/wiki/Emi_Koussi'),
('Piz Linard', '/wiki/Piz_Linard'),
('Mount Woolley', '/wiki/Mount_Woolley'),
('Aneto', '/wiki/Aneto'),
('Fluchthorn', '/wiki/Fluchthorn'),
('Grand Bec', '/wiki/Grand_Bec'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Rockchuck Peak', '/wiki/Rockchuck_Peak'),
('Pico Veleta', '/wiki/Veleta_(Sierra_Nevada)'),
('Mount Hector', '/wiki/Mount_Hector_(Alberta)'),
('Piz Platta', '/wiki/Piz_Platta'),
('Telescope Peak', '/wiki/Telescope_Peak'),
('Champagne Castle', '/wiki/Champagne_Castle'),
('Pic Uzu', '/w/index.php?title=Pic_Uzu&action=edit&redlink=1'),
('Cerro Chaltén', '/wiki/Cerro_Chalt%C3%A9n'),
('Mount Spurr', '/wiki/Mount_Spurr'),
('Pointe du Vallonnet', '/wiki/Pointe_du_Vallonnet'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Mammoth Mountain', '/wiki/Mammoth_Mountain'),
('Fründenhorn', '/wiki/Fr%C3%BCndenhorn'),
('Pointe Renod', '/wiki/Pointe_Renod'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Traverse Peak', '/wiki/Traverse_Peak'),
('Mount Edith Cavell', '/wiki/Mount_Edith_Cavell'),
('Dôme des Sonnailles', '/wiki/D%C3%B4me_des_Sonnailles'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Mount Agepsta', '/wiki/Mount_Agepsta'),
('Gagra Range', '/wiki/Gagra_Range'),
('Mount Munday', '/wiki/Mount_Munday'),
('Pointe de Claret', '/wiki/Pointe_de_Claret'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Monte Perdido', '/wiki/Monte_Perdido'),
('Electric Peak', '/wiki/Electric_Peak'),
('Mount Saskatchewan', '/wiki/Mount_Saskatchewan_(Alberta)'),
('Cerro Fábrega', '/wiki/Cerro_F%C3%A1brega'),
('Ward Mountain', '/wiki/Ward_Mountain_(Nevada)'),
('Pointe de Méan Martin', '/wiki/Pointe_de_M%C3%A9an_Martin'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Dôme de Polset', '/wiki/D%C3%B4me_de_Polset'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Cathedral Peak', '/wiki/Cathedral_Peak_(California)'),
('Raynolds Peak', '/wiki/Raynolds_Peak'),
('Rolling Thunder Mountain', '/wiki/Rolling_Thunder_Mountain'),
('Mount Hampton', '/wiki/Mount_Hampton'),
('Dôme des Pichères', '/wiki/D%C3%B4me_des_Pich%C3%A8res'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Grand Roc', '/wiki/Grand_Roc'),
('Vanoise massif', '/wiki/Vanoise_massif'),
("Giant's Castle", '/wiki/Giant%27s_Castle'),
('Sunwapta Peak', '/wiki/Sunwapta_Peak'),
('Piz Buin', '/wiki/Piz_Buin'),
('Mount Ball', '/wiki/Mount_Ball'),
('Piz Badile', '/wiki/Piz_Badile'),
('Mount Chephren', '/wiki/Mount_Chephren'),
('Ağ Dağ', '/wiki/A%C4%9F_Da%C4%9F'),
('Bozgush mountain range', '/wiki/Mount_Bozgush'),
('Mount Silberhorn', '/wiki/Mount_Silberhorn'),
('San Jacinto Peak', '/wiki/San_Jacinto_Peak'),
('Didi Abuli', '/wiki/Didi_Abuli'),
('Bivouac Peak', '/wiki/Bivouac_Peak'),
('Mount Wilbur', '/wiki/Mount_Wilbur_(Alaska)'),
('Monte Argentera', '/wiki/Monte_Argentera'),
('Mount Rose (Nevada)', '/wiki/Mount_Rose_(Nevada)'),
('Carson Range', '/wiki/Carson_Range'),
('Mount Samsari', '/wiki/Mount_Samsari'),
('Roche Chevrière', '/wiki/Roche_Chevri%C3%A8re'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Habicht', '/wiki/Habicht'),
('Thompson Peak', '/wiki/Thompson_Peak_(Idaho)'),
('Pointe de Thorens', '/wiki/Pointe_de_Thorens'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Mount Cramer', '/wiki/Mount_Cramer'),
('Toussidé', '/wiki/Toussid%C3%A9'),
('Antelao', '/wiki/Antelao'),
('Mont Pelve', '/wiki/Mont_Pelve'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Mount Stanley Baldwin', '/wiki/Mount_Stanley_Baldwin'),
('Sandia Crest', '/wiki/Sandia_Mountains'),
('Épaule du Bouchet', '/wiki/%C3%89paule_du_Bouchet'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Mount Smythe', '/wiki/Mount_Smythe'),
('Wildstrubel', '/wiki/Wildstrubel'),
('Williams Peak', '/wiki/Williams_Peak_(Idaho)'),
('Mount Hope', '/wiki/Mount_Hope_(Eternity_Range)'),
('Titlis', '/wiki/Titlis'),
('Owl Peak', '/wiki/Owl_Peak'),
('Mount Mackenzie King', '/wiki/Mount_Mackenzie_King'),
('Pointe des Buffettes', '/wiki/Pointe_des_Buffettes'),
('Lisenser Spitze', '/wiki/Lisenser_Spitze'),
('Mount Terror', '/wiki/Mount_Terror_(Antarctica)'),
('Aiguille Rouge', '/wiki/Aiguille_Rouge'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Monte Civetta', '/wiki/Monte_Civetta'),
('Symmetry Spire', '/wiki/Symmetry_Spire'),
('Glacier Peak', '/wiki/Glacier_Peak'),
('Pointe du Dard', '/wiki/Pointe_du_Dard'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Mount Binalud', '/wiki/Mount_Binalud'),
('Alborz', '/wiki/Alborz'),
('Pointe de la Réchasse', '/wiki/Pointe_de_la_R%C3%A9chasse'),
('Vanoise massif', '/wiki/Vanoise_massif'),
('Mount Jefferson', '/wiki/Mount_Jefferson_(Montana)'),
('Mount Jefferson', '/wiki/Mount_Jefferson_(Oregon)'),
('Dreiländerspitze', '/wiki/Dreil%C3%A4nderspitze'),
('Mount Kita', '/wiki/Mount_Kita'),
('Akaishi Mountains', '/wiki/Akaishi_Mountains'),
('Mount Hotaka', '/wiki/Mount_Hotaka_(Nagano,_Gifu)'),
('Hida Mountains', '/wiki/Hida_Mountains'),
('Mount Cleveland', '/wiki/Mount_Cleveland_(Montana)'),
('Ainodake', '/wiki/Ainodake'),
('Lassen Peak', '/wiki/Lassen_Peak'),
('Mount Galatea', '/wiki/Mount_Galatea'),
('Rendezvous Mountain', '/wiki/Rendezvous_Mountain'),
('Saviers Peak', '/wiki/Saviers_Peak'),
('Mount Yari', '/wiki/Mount_Yari'),
('Parícutin', '/wiki/Par%C3%ADcutin'),
('Mount Aylmer', '/wiki/Mount_Aylmer'),
('South Sister', '/wiki/Three_Sisters_(Oregon)'),
('Stanley Peak', '/wiki/Stanley_Peak_(Ball_Range)'),
('Jøkulkyrkja', '/wiki/J%C3%B8kulkyrkja'),
("Pica d'Estats", '/wiki/Pica_d%27Estats'),
('Mount Arakawa', '/wiki/Mount_Warusawa'),
('Gray Peak', '/wiki/Gray_Peak_(Wyoming)'),
('Mount Heyburn', '/wiki/Mount_Heyburn'),
('Mount Washburn', '/wiki/Mount_Washburn'),
('Mount Collie', '/wiki/Mount_Collie'),
('Mount Siple', '/wiki/Mount_Siple'),
('Pirchinassi', '/wiki/Pirchinassi'),
('Mount Redoubt', '/wiki/Mount_Redoubt_(Alaska)'),
('Mount Babel', '/wiki/Mount_Babel_(Alberta)'),
('Mount Emei', '/wiki/Mount_Emei'),
('Pico Duarte', '/wiki/Pico_Duarte'),
('Trapper Peak', '/wiki/Trapper_Peak_(Montana)'),
('Storm Mountain', '/wiki/Storm_Mountain_(Alberta)'),
('Mount Blackmore', '/wiki/Mount_Blackmore'),
('Mount Stimson', '/wiki/Mount_Stimson'),
('Mol Len', '/wiki/Mol_Len'),
('Qurnat as Sawdā’', '/wiki/Qurnat_as_Sawd%C4%81%E2%80%99'),
('Mount Richardson', '/wiki/Mount_Richardson_(Alberta)'),
('Kintla Peak', '/wiki/Kintla_Peak'),
('Mount Moulton', '/wiki/Mount_Moulton'),
('Smoky Dome', '/wiki/Smoky_Dome'),
('North Sister', '/wiki/Three_Sisters_(Oregon)'),
('Piton des Neiges', '/wiki/Piton_des_Neiges'),
('Mount San Antonio', '/wiki/Mount_San_Antonio'),
('Mount Ontake', '/wiki/Mount_Ontake'),
('Mount Jackson', '/wiki/Mount_Jackson_(Montana)'),
('Middle Sister', '/wiki/Three_Sisters_(Oregon)'),
('Mount Wutai', '/wiki/Mount_Wutai'),
('Mount Nyamuragira', '/wiki/Mount_Nyamuragira'),
('Haleakala', '/wiki/Haleakala'),
('Crowfoot Mountain', '/wiki/Crowfoot_Mountain_(Alberta)'),
('Mount Chester', '/wiki/Mount_Chester'),
('Mount Siyeh', '/wiki/Mount_Siyeh'),
('Mount Merritt', '/wiki/Mount_Merritt'),
('Cerro de Coxóm', '/wiki/Cerro_de_Cox%C3%B3m'),
('Parseierspitze', '/wiki/Parseierspitze'),
('Mount Senjō', '/wiki/Mount_Senj%C5%8D'),
('Mount Aspiring/Tititea', '/wiki/Mount_Aspiring/Tititea'),
('Kinnerly Peak', '/wiki/Kinnerly_Peak'),
('Mount Agung', '/wiki/Mount_Agung'),
('Mount McArthur', '/wiki/Mount_McArthur_(British_Columbia)'),
('Mount Norikura', '/wiki/Mount_Norikura'),
('Tsiteli Khati', '/wiki/Tsiteli_Khati'),
('Mount Tate', '/wiki/Mount_Tate'),
('Mount Japvo', '/w/index.php?title=Mount_Japvo&action=edit&redlink=1'),
('Mount Tahat', '/wiki/Mount_Tahat'),
('Sapitwa', '/wiki/Sapitwa'),
('The Fortress', '/wiki/The_Fortress_(Alberta)'),
('Sacajawea Peak', '/wiki/Sacajawea_Peak'),
('Pizzo Centrale', '/wiki/Pizzo_Centrale'),
('Cascade Mountain', '/wiki/Cascade_Mountain_(Alberta)'),
('Copahue', '/wiki/Copahue'),
('Mount Girouard', '/wiki/Mount_Girouard'),
('Pico da Neblina', '/wiki/Pico_da_Neblina'),
('Mount Whyte', '/wiki/Mount_Whyte'),
('Miranjani', '/wiki/Miranjani'),
('Forellen Peak', '/wiki/Forellen_Peak'),
('Mount Andrus', '/wiki/Mount_Andrus'),
('Mount Niblock', '/wiki/Mount_Niblock'),
('Pico 31 de Março', '/wiki/Pico_31_de_Mar%C3%A7o'),
('Keele Peak', '/wiki/Keele_Peak'),
('Mount Odin', '/wiki/Mount_Odin_(British_Columbia)'),
('Schilthorn', '/wiki/Schilthorn'),
('Mount Tallac', '/wiki/Mount_Tallac'),
('Mount Inglismaldie', '/wiki/Mount_Inglismaldie'),
('Mount Ramelau', '/wiki/Mount_Ramelau'),
('Zugspitze', '/wiki/Zugspitze'),
('Slide Mountain (Nevada)', '/wiki/Slide_Mountain_(Nevada)'),
('Carson Range', '/wiki/Carson_Range'),
('Little Alberta', '/wiki/Little_Alberta'),
('Mount Arfak', '/wiki/Mount_Arfak'),
('Arfak Mountains', '/wiki/Arfak_Mountains'),
('Iron Mountain', '/wiki/Iron_Mountain_(Idaho)'),
('Apo', '/wiki/Mount_Apo'),
('Fossil Mountain', '/wiki/Fossil_Mountain_(Alberta)'),
('Coma Pedrosa', '/wiki/Coma_Pedrosa'),
('Going to the Sun Mountain', '/wiki/Going_to_the_Sun_Mountain'),
('Fishers Peak', '/wiki/Fishers_Peak'),
('Pilot Mountain', '/wiki/Pilot_Mountain_(Alberta)'),
('Uri Rotstock', '/wiki/Uri_Rotstock'),
('Musala', '/wiki/Musala'),
('Mount Pulag', '/wiki/Mount_Pulag'),
('Mount Olympus', '/wiki/Mount_Olympus'),
('Mount Gould', '/wiki/Mount_Gould_(Montana)'),
('Mount Blakiston', '/wiki/Mount_Blakiston'),
('Mount Sas dla Crusc', '/w/index.php?title=Mount_Sas_dla_Crusc&action=edit&redlink=1'),
('Chutine Peak', '/wiki/Chutine_Peak'),
('Rising Wolf Mountain', '/wiki/Rising_Wolf_Mountain'),
('Bonanza Peak', '/wiki/Bonanza_Peak_(Washington)'),
('Pic de Sanfonts', '/wiki/Pic_de_Sanfonts'),
('Pico da Bandeira', '/wiki/Pico_da_Bandeira'),
('Collarada', '/wiki/Collarada'),
('Boardman Peak', '/wiki/Boardman_Peak'),
('Mount Wrightson', '/wiki/Mount_Wrightson'),
('Lembert Dome', '/wiki/Lembert_Dome'),
('Mount Stuart', '/wiki/Mount_Stuart'),
('Mount Silverthrone', '/wiki/Mount_Silverthrone'),
('Triglav', '/wiki/Triglav'),
('Mount Saint Nicholas', '/wiki/Mount_Saint_Nicholas'),
('Mount Wilbur', '/wiki/Mount_Wilbur_(Montana)'),
('Pico do Fogo', '/wiki/Pico_do_Fogo'),
('Cape Verde', '/wiki/Cape_Verde'),
('Mount Fernow', '/wiki/Mount_Fernow'),
('Mount Hermon', '/wiki/Mount_Hermon'),
('Mount Cory', '/wiki/Mount_Cory_(Alberta)'),
('Mount Thielsen', '/wiki/Mount_Thielsen'),
('Pedra da Mina', '/wiki/Pedra_da_Mina'),
('Mount Ruapehu', '/wiki/Mount_Ruapehu'),
('Copper Mountain', '/wiki/Copper_Mountain_(Alberta)'),
('Pico das Agulhas Negras', '/wiki/Pico_das_Agulhas_Negras'),
('Hayes Volcano', '/wiki/Hayes_Volcano'),
('Mount Edziza', '/wiki/Mount_Edziza'),
('Canigou', '/wiki/Canigou'),
('Mount Longonot', '/wiki/Mount_Longonot'),
('Buckner Mountain', '/wiki/Buckner_Mountain'),
('Mount Longonot', '/wiki/Mount_Longonot'),
('Seven Fingered Jack', '/wiki/Seven_Fingered_Jack'),
('Mount Nirvana', '/wiki/Mount_Nirvana'),
('Pico do Cristal', '/w/index.php?title=Pico_do_Cristal&action=edit&redlink=1'),
('Chief Mountain', '/wiki/Chief_Mountain'),
('Lincoln Peak', '/wiki/Lincoln_Peak_(Washington)'),
('Castle Mountain', '/wiki/Castle_Mountain'),
('Pyramid Mountain', '/wiki/Pyramid_Mountain_(Alberta)'),
('Mount Bachelor', '/wiki/Mount_Bachelor'),
('Mount Korab', '/wiki/Mount_Korab'),
('Mount Sir James MacBrien', '/wiki/Mount_Sir_James_MacBrien'),
('Mount Olympus', '/wiki/Mount_Olympus_(Utah)'),
('Mawson Peak', '/wiki/Mawson_Peak'),
('Mount Bukhan', '/wiki/Mount_Bukhan'),
('Fairview Mountain', '/wiki/Fairview_Mountain_(Alberta)'),
('Mount Baekdu', '/wiki/Mount_Baekdu'),
('Škrlatica', '/wiki/%C5%A0krlatica'),
('Monte Roraima', '/wiki/Monte_Roraima'),
('Heavens Peak', '/wiki/Heavens_Peak'),
('Mount Spickard', '/wiki/Mount_Spickard'),
('North Cascades', '/wiki/North_Cascades'),
('Mount Melbourne', '/wiki/Mount_Melbourne'),
('Cerro El Pital', '/wiki/Cerro_El_Pital'),
('Mount Redoubt', '/wiki/Mount_Redoubt_(Washington)'),
('Pizzo di Claro', '/wiki/Pizzo_di_Claro'),
('Mount Morning', '/wiki/Mount_Morning'),
('Serles', '/wiki/Serles'),
('Watzmann', '/wiki/Watzmann'),
('Boston Peak', '/wiki/Boston_Peak'),
('Schiahorn', '/wiki/Schiahorn'),
('Grotto Mountain', '/wiki/Grotto_Mountain'),
('Mount Haku', '/wiki/Mount_Haku'),
('Ryōhaku Mountains', '/wiki/Ry%C5%8Dhaku_Mountains'),
('Eldorado Peak', '/wiki/Eldorado_Peak'),
('Anaimudi', '/wiki/Anamudi'),
('Maja Jezerce', '/wiki/Maja_Jezerce'),
('Half Dome', '/wiki/Half_Dome'),
('Mount Louis', '/wiki/Mount_Louis'),
('Mount Discovery', '/wiki/Mount_Discovery'),
('Morro do Couto', '/w/index.php?title=Morro_do_Couto&action=edit&redlink=1'),
('Pic de la Selle', '/wiki/Pic_de_la_Selle'),
('Mount Garibaldi', '/wiki/Mount_Garibaldi'),
('Pedra do Sino', '/w/index.php?title=Pedra_do_Sino&action=edit&redlink=1'),
('Guadalupe Peak', '/wiki/Guadalupe_Peak'),
('Guadalupe Mountains', '/wiki/Guadalupe_Mountains'),
('Großer Krottenkopf', '/wiki/Gro%C3%9Fer_Krottenkopf'),
('Allgäu Alps', '/wiki/Allg%C3%A4u_Alps'),
('Pic del Port Vell', '/wiki/Pic_del_Port_Vell'),
('Gerlachov Peak', '/wiki/Gerlachov_Peak'),
('Mount Michelson', '/wiki/Mount_Michelson_(Chugach_Mountains)'),
('Mount St. Piran', '/wiki/Mount_St._Piran'),
('Mount Meager', '/wiki/Mount_Meager'),
('Mount Trus Madi', '/wiki/Mount_Trus_Madi'),
('Doddabetta', '/wiki/Doddabetta'),
('Piton de la Fournaise', '/wiki/Piton_de_la_Fournaise'),
('Mount Crean', '/wiki/Mount_Crean'),
('Cardinal Peak', '/wiki/Cardinal_Peak'),
('Barbeau Peak', '/wiki/Barbeau_Peak'),
('Pelister Peak', '/wiki/Baba_Mountain,_Macedonia'),
('Pico Almanzor', '/wiki/Pico_Almanzor'),
('Pizzo Molare', '/wiki/Pizzo_Molare'),
('Mount Tavkvetili', '/wiki/Mount_Tavkvetili'),
('Argonaut Peak', '/wiki/Argonaut_Peak'),
('Doi Inthanon', '/wiki/Doi_Inthanon'),
('Thailand', '/wiki/Thailand'),
("Cooke's Peak/Cook's Peak", '/w/index.php?title=Cooke%27s_Peak/Cook%27s_Peak&action=edit&redlink=1'),
('Pic dels Aspres', '/wiki/Pic_dels_Aspres'),
('Aguja Saint Exupery', '/wiki/Aguja_Saint_Exupery'),
('Mount St. Helens', '/wiki/Mount_St._Helens'),
('Big Hatchet Peak', '/wiki/Big_Hatchet_Peak'),
('Moldoveanu Peak', '/wiki/Moldoveanu_Peak'),
('Negoiu Peak', '/wiki/Negoiu_Peak'),
('Vistea Mare', '/wiki/Vistea_Mare'),
('Pidurutalagala', '/wiki/Pidurutalagala'),
('Mount Norquay', '/wiki/Mount_Norquay'),
('Hualalai', '/wiki/Hualalai'),
('Parangu Mare', '/wiki/Parangu_Mare'),
('Mount Taranaki/Egmont', '/wiki/Mount_Taranaki/Egmont'),
('Garfield Peak', '/wiki/Garfield_Peak_(Wyoming)'),
('Mount Veniaminof', '/wiki/Mount_Veniaminof'),
('Omu Peak', '/w/index.php?title=Omu_Peak&action=edit&redlink=1'),
('Rysy', '/wiki/Rysy'),
('Pindus', '/wiki/Pindus'),
('Špik', '/wiki/%C5%A0pik'),
('Luna Peak', '/wiki/Luna_Peak_(British_Columbia)'),
('Galdhøpiggen', '/wiki/Galdh%C3%B8piggen'),
('Glittertind', '/wiki/Glittertind'),
('El Capitan', '/wiki/El_Capitan_(Texas)'),
('Shimbiris', '/wiki/Shimbiris'),
('Sulphur Mountain', '/wiki/Sulphur_Mountain_(Alberta)'),
('Sunset Crater', '/wiki/Sunset_Crater'),
('Faraya Mzaar', '/w/index.php?title=Faraya_Mzaar&action=edit&redlink=1'),
('Triple Divide Peak', '/wiki/Triple_Divide_Peak_(Montana)'),
('Monte Binga', '/wiki/Monte_Binga'),
('Mount Olympus', '/wiki/Mount_Olympus_(Washington)'),
('Peñalara', '/wiki/Pe%C3%B1alara'),
('Mount Dobong', '/w/index.php?title=Mount_Dobong&action=edit&redlink=1'),
('Mount Daniel', '/wiki/Mount_Daniel'),
('Mount Murud', '/wiki/Mount_Murud'),
('Mocho', '/wiki/Mocho-Choshuenco'),
('Choshuenco', '/wiki/Mocho-Choshuenco'),
('Ivis Peak', '/w/index.php?title=Ivis_Peak&action=edit&redlink=1'),
('Ha Ling Peak', '/wiki/Ha_Ling_Peak'),
('Store Skagastølstind', '/wiki/Store_Skagast%C3%B8lstind'),
('Hajla', '/wiki/Hajla'),
('Le Tabor', '/wiki/Le_Tabor'),
('Kirigalpottha', '/wiki/Kirigalpottha'),
('Maglić', '/wiki/Magli%C4%87_(mountain)'),
('Mount Cayley', '/wiki/Mount_Cayley'),
('Mount Galwey', '/wiki/Mount_Galwey'),
('Botev Peak', '/wiki/Botev_Peak'),
('Mount Mulu', '/wiki/Mount_Mulu'),
('Mount Deception', '/wiki/Mount_Deception_(Washington)'),
('Mount Karthala', '/wiki/Mount_Karthala'),
('Totapala Kanda', '/w/index.php?title=Totapala_Kanda&action=edit&redlink=1'),
('Signal Mountain', '/wiki/Signal_Mountain_(Wyoming)'),
('Mount Pico', '/wiki/Mount_Pico'),
('Azores, Portugal', '/wiki/Azores,_Portugal'),
('Mount Blum', '/wiki/Mount_Blum'),
('North Cascades', '/wiki/North_Cascades'),
('Mount Popomanaseu', '/wiki/Mount_Popomanaseu'),
('Mount Prophet', '/wiki/Mount_Prophet'),
('North Cascades', '/wiki/North_Cascades'),
('Mount Griggs', '/wiki/Mount_Griggs'),
('Mount Makarakomburu', '/wiki/Mount_Makarakomburu'),
('Lalla Khedidja', '/wiki/Lalla_Khedidja'),
('Lavender Peak', '/wiki/Lavender_Peak_(British_Columbia)'),
('Pietrosul Rodnei Peak', '/w/index.php?title=Pietrosul_Rodnei_Peak&action=edit&redlink=1'),
('Mount Sir Allan MacNab', '/wiki/Mount_Sir_Allan_MacNab'),
('Murree', '/wiki/Murree'),
('Druesberg', '/wiki/Druesberg'),
('Ineu Peak', '/wiki/Ineu_Peak'),
('Bikku Bitti', '/wiki/Bikku_Bitti'),
('Sri Pada Mountain', '/wiki/Adam%27s_Peak'),
('Mount John Laurie', '/wiki/Mount_John_Laurie'),
('Red Butte', '/wiki/Red_Butte'),
('Čvrsnica', '/wiki/%C4%8Cvrsnica'),
('Herzegovina', '/wiki/Herzegovina'),
('Mount Kosciuszko', '/wiki/Mount_Kosciuszko'),
('Camoghe', '/wiki/Camoghe'),
('Mount Chiginagak', '/wiki/Mount_Chiginagak'),
('Mount Townsend', '/wiki/Mount_Townsend'),
('Black Elk Peak', '/wiki/Black_Elk_Peak'),
('Golden Hinde', '/wiki/Golden_Hinde_(British_Columbia)'),
('Mount Twynam', '/wiki/Mount_Twynam'),
('Elkhorn Mountain', '/wiki/Elkhorn_Mountain'),
('Mount Baldy', '/wiki/Mount_Baldy_(Alberta)'),
('Shiprock', '/wiki/Shiprock'),
('Mount Tahan', '/wiki/Mount_Tahan'),
('Mount Korbu', '/wiki/Mount_Korbu'),
('Mount Yong Belar', '/wiki/Mount_Yong_Belar'),
('Doi Chiang Dao', '/wiki/Doi_Chiang_Dao'),
('Galunggung', '/wiki/Galunggung'),
('Mount Hua', '/wiki/Mount_Hua'),
('Carruthers Peak', '/wiki/Carruthers_Peak'),
('Crna Glava', '/wiki/Crna_Glava'),
('Mount Colonel Foster', '/wiki/Mount_Colonel_Foster'),
('Roche à Perdrix', '/wiki/Roche_%C3%A0_Perdrix'),
('Kodaikanal', '/wiki/Kodaikanal'),
('Pilatus', '/wiki/Pilatus_(mountain)'),
('Strmenica', '/wiki/Strmenica'),
('Phu Soi Dao', '/wiki/Phu_Soi_Dao'),
('Eagle Peak', '/wiki/Eagle_Peak_(Alaska)'),
('Zekova Glava', '/w/index.php?title=Zekova_Glava&action=edit&redlink=1'),
('Öræfajökull', '/wiki/%C3%96r%C3%A6faj%C3%B6kull'),
('Mount Benum', '/wiki/Mount_Benum'),
('Mogotón', '/wiki/Mogot%C3%B3n'),
('Kebnekaise', '/wiki/Kebnekaise'),
('Rambler Peak', '/wiki/Rambler_Peak'),
('Mount McBride', '/wiki/Mount_McBride'),
('Pico do Selado', '/w/index.php?title=Pico_do_Selado&action=edit&redlink=1'),
('Phou Khe', '/wiki/Phou_Khe'),
('Schneeberg', '/wiki/Schneeberg_(Alps)'),
('Mount Tate', '/wiki/Mount_Tate_(New_South_Wales)'),
('Bjelašnica', '/wiki/Bjela%C5%A1nica'),
('Kings Peak', '/wiki/Kings_Peak_(British_Columbia)'),
('Hoverla', '/wiki/Hoverla'),
('Mount Katmai', '/wiki/Mount_Katmai'),
('Mount Dimlang', '/wiki/Mount_Dimlang'),
('Mount Celeste', '/wiki/Mount_Celeste'),
('Mount Mitchell', '/wiki/Mount_Mitchell'),
('Yancey County, North Carolina', '/wiki/Yancey_County,_North_Carolina'),
('Namunukula', '/wiki/Namunukula'),
('Mount Batu Brinchang', '/wiki/Mount_Batu_Brinchang'),
('Doi Mae Tho', '/wiki/Doi_Mae_Tho'),
('Clingmans Dome', '/wiki/Clingmans_Dome'),
('Mount Heng (Shanxi)', '/wiki/Mount_Heng_(Shanxi)'),
('Kopaonik', '/wiki/Kopaonik'),
("Pančić's Peak", '/wiki/Pan%C4%8Di%C4%87%27s_Peak'),
('Polar Bear Peak', '/wiki/Polar_Bear_Peak'),
('Mount Asgard', '/wiki/Mount_Asgard'),
('Mount Le Conte', '/wiki/Mount_Le_Conte_(Tennessee)'),
('Serra da Estrela', '/wiki/Serra_da_Estrela'),
('Mount Bogong', '/wiki/Mount_Bogong'),
('Mount Ishizuchi', '/wiki/Mount_Ishizuchi'),
('Doi Phu Kha', '/wiki/Doi_Phu_Kha'),
('Luang Prabang Range', '/wiki/Luang_Prabang_Range'),
('Topo de Coroa', '/wiki/Topo_de_Coroa'),
('Mount Tongariro', '/wiki/Mount_Tongariro'),
('Iceberg Peak', '/wiki/Iceberg_Peak'),
('Pico Turquino', '/wiki/Pico_Turquino'),
('El Piveto Mountain', '/wiki/El_Piveto_Mountain'),
('Qiajivik Mountain', '/wiki/Qiajivik_Mountain'),
('Monte Tamaro', '/wiki/Monte_Tamaro'),
('Farcau Peak', '/w/index.php?title=Farcau_Peak&action=edit&redlink=1'),
('Ciucas Peak', '/wiki/Ciucas_Peak'),
('Chionistra', '/wiki/Chionistra'),
('Hallasan', '/wiki/Hallasan'),
('Jabal Bil Ays', '/wiki/Jabal_Bil_Ays'),
('Mullayanagiri', '/wiki/Mullayanagiri'),
('Mount Kirigamine', '/wiki/Mount_Kirigamine'),
('Mount Washington', '/wiki/Mount_Washington_(New_Hampshire)'),
('Presidential Range', '/wiki/Presidential_Range'),
('Mount Jiri', '/wiki/Mount_Jiri'),
('Troglav', '/wiki/Troglav_(Bosnia_and_Herzegovina)'),
('Mont Ventoux', '/wiki/Mont_Ventoux'),
('Ocolasu Mare', '/w/index.php?title=Ocolasu_Mare&action=edit&redlink=1'),
('Mount Toaca', '/w/index.php?title=Mount_Toaca&action=edit&redlink=1'),
('Vesper Peak', '/wiki/Vesper_Peak'),
('Baba Budangiri', '/wiki/Baba_Budangiri'),
('Narodnaya', '/wiki/Narodnaya'),
('Kudremukh', '/wiki/Kudremukh'),
('Orjen', '/wiki/Orjen'),
('Mount George V', '/wiki/Mount_George_V'),
('Rugged Mountain', '/wiki/Rugged_Mountain'),
('Straja', '/wiki/Straja'),
('Trident Volcano', '/wiki/Trident_Volcano'),
('Mount Martin', '/wiki/Mount_Martin_(Alaska)'),
('Knuckles', '/wiki/Knuckles_Mountain_Range'),
('Pico Ruivo', '/wiki/Pico_Ruivo'),
('Budacu', '/w/index.php?title=Mount_Budacu&action=edit&redlink=1'),
('Giumalau', '/w/index.php?title=Giumalau&action=edit&redlink=1'),
('Mont Ross', '/wiki/Mont_Ross'),
('Cucurbata Mare', '/wiki/Cucurbata_Mare'),
('Crown Mountain', '/wiki/Crown_Mountain_(Vancouver_Island,_British_Columbia)'),
('Tibles', '/w/index.php?title=Tibles&action=edit&redlink=1'),
('Loser', '/wiki/Loser_(mountain)'),
('Vladeasa', '/w/index.php?title=Vladeasa&action=edit&redlink=1'),
('Sinjal', '/w/index.php?title=Sinjal&action=edit&redlink=1'),
('Cerro La Campana', '/wiki/Cerro_La_Campana'),
('Muntele Mare', '/w/index.php?title=Muntele_Mare&action=edit&redlink=1'),
('Cerro de la Silla', '/wiki/Cerro_de_la_Silla'),
('Biligiriranga Hills', '/wiki/Biligiriranga_Hills'),
('Rigi', '/wiki/Rigi'),
('Hășmașu Mare', '/w/index.php?title=H%C4%83%C8%99ma%C8%99u_Mare&action=edit&redlink=1'),
('Pietrosu Peak', '/w/index.php?title=Pietrosu_Peak&action=edit&redlink=1'),
('Goru', '/wiki/Goru'),
('Velliangiri Mountains', '/wiki/Velliangiri_Mountains'),
('Lacaut', '/w/index.php?title=Lacaut&action=edit&redlink=1'),
('Saca Peak', '/w/index.php?title=Saca_Peak&action=edit&redlink=1'),
('Penteleu', '/wiki/Penteleu'),
('Mount Veve', '/wiki/Mount_Veve'),
('Mount Adams', '/wiki/Mount_Adams_(New_Hampshire)'),
('Sveti Jure (Saint George)', '/w/index.php?title=Sveti_Jure_(Saint_George)&action=edit&redlink=1'),
('Vaganski vrh', '/w/index.php?title=Vaganski_vrh&action=edit&redlink=1'),
('Mount Api', '/wiki/Mount_Api'),
('Tadiandamol', '/wiki/Tadiandamol'),
('Mount Rogers', '/wiki/Mount_Rogers'),
('Doi Phi Pan Nam', '/wiki/Doi_Phi_Pan_Nam'),
('Mount Wilson', '/wiki/Mount_Wilson_(California)'),
('Mount Jefferson', '/wiki/Mount_Jefferson'),
('Daisen', '/wiki/Daisen_(mountain)'),
('The Horn (Mount Buffalo)', '/wiki/The_Horn_(Mount_Buffalo)'),
('Mount Batur', '/wiki/Mount_Batur'),
('Kumara Parvata', '/wiki/Kumara_Parvata'),
('Pushpagiri', '/wiki/Pushpagiri,_Karnataka'),
('Mount Lowe', '/wiki/Mount_Lowe_(California)'),
('Boulder Peak', '/wiki/Boulder_Peak_(Washington)'),
('Doi Luang', '/wiki/Doi_Luang,_Phi_Pan_Nam_Range'),
('Mitre Peak', '/wiki/Mitre_Peak_(New_Zealand)'),
('Arma Konda', '/wiki/Arma_Konda'),
('Deomali', '/wiki/Deomali_(mountain)'),
('Mount Caubvik', '/wiki/Mount_Caubvik'),
('Rarau', '/w/index.php?title=Rarau&action=edit&redlink=1'),
('Peak 5390', '/wiki/Peak_5390'),
('Yamantau', '/wiki/Yamantau'),
('Mount Monroe', '/wiki/Mount_Monroe'),
('Mount Madison', '/wiki/Mount_Madison'),
('Mount Marcy', '/wiki/Mount_Marcy_(New_York)'),
('Velky Rozsutec', '/wiki/Velky_Rozsutec'),
('Brahmagiri', '/wiki/Brahmagiri_(hill)'),
('Mount Katahdin', '/wiki/Mount_Katahdin'),
('Sněžka', '/wiki/Sn%C4%9B%C5%BEka'),
('Sirumalai', '/wiki/Sirumalai'),
('Mount Lafayette', '/wiki/Mount_Lafayette'),
('Mount Washington (British Columbia)', '/wiki/Mount_Washington_(British_Columbia)'),
('Mount Benarat', '/wiki/Mount_Benarat'),
("Wai'ale'ale", '/wiki/Wai%27ale%27ale'),
('Mount Baw Baw', '/wiki/Mount_Baw_Baw'),
('Cirque Mountain', '/wiki/Cirque_Mountain'),
('Mount Lincoln', '/wiki/Mount_Lincoln'),
('Superstition Mountain', '/wiki/Superstition_Mountain'),
('Mount Tai', '/wiki/Mount_Tai'),
('Jabel Yibir', '/wiki/Jabel_Yibir'),
('Madikeri', '/wiki/Madikeri'),
('Mount Popa', '/wiki/Mount_Popa'),
('Askja', '/wiki/Askja'),
('Monte Boglia', '/wiki/Monte_Boglia'),
('Kamakau', '/wiki/Kamakau'),
('Song Shan', '/wiki/Mount_Song'),
('Javaleon', '/wiki/Javaleon'),
('Mount Nuang', '/wiki/Mount_Nuang'),
('Hekla', '/wiki/Hekla'),
('Mount Pinatubo', '/wiki/Mount_Pinatubo'),
('Spruce Knob', '/wiki/Spruce_Knob'),
('Mount Olympus', '/wiki/Mount_Olympus_(Tasmania)'),
('Tasmania', '/wiki/Tasmania'),
('Agriolefkes', '/w/index.php?title=Agriolefkes&action=edit&redlink=1'),
('Mount Seymour', '/wiki/Mount_Seymour'),
('Himavad Gopalaswamy Betta', '/wiki/Himavad_Gopalaswamy_Betta'),
('Snæfellsjökull', '/wiki/Sn%C3%A6fellsj%C3%B6kull'),
('Gutai Peak', '/w/index.php?title=Gutai_Peak&action=edit&redlink=1'),
('Mount Kalourat', '/wiki/Mount_Kalourat'),
('Cypress Mountain', '/wiki/Cypress_Mountain'),
('Yelagiri', '/wiki/Yelagiri'),
('Parasnath', '/wiki/Parasnath'),
('Dhupgarh', '/wiki/Dhupgarh'),
('Ben Nevis', '/wiki/Ben_Nevis'),
('Kodachadri', '/wiki/Kodachadri'),
('Mount Jiuhua', '/wiki/Mount_Jiuhua'),
('Mount Aniakchak', '/wiki/Mount_Aniakchak'),
('Cerro de Punta', '/wiki/Cerro_de_Punta'),
('Mount Bassie', '/wiki/Mount_Bassie'),
('Ben Macdhui', '/wiki/Ben_Macdhui_(Scotland)'),
('Mount Kanaga', '/wiki/Mount_Kanaga'),
('Sinhagad', '/wiki/Sinhagad'),
('Mount Heng (Hunan)', '/wiki/Mount_Heng_(Hunan)'),
('Rajabasa', '/wiki/Rajabasa'),
('Mount Vesuvius', '/wiki/Mount_Vesuvius'),
('Mount Ophir', '/wiki/Mount_Ophir'),
('Bailadila', '/wiki/Bailadila'),
('Mount Wellington', '/wiki/Mount_Wellington_(Tasmania)'),
('Mount Si', '/wiki/Mount_Si'),
('Mount Qingcheng', '/wiki/Mount_Qingcheng'),
('Detunata', '/wiki/Detunata'),
('Mount Donna Buang', '/wiki/Mount_Donna_Buang'),
("Camel's Hump", '/wiki/Camel%27s_Hump_(Vermont)'),
('Cannon Mountain', '/wiki/Cannon_Mountain_(New_Hampshire)'),
('The Priest', '/wiki/The_Priest_(mountain)'),
('Grouse Mountain', '/wiki/Grouse_Mountain'),
('Kaʻala', '/wiki/Ka%CA%BBala'),
('Mount Jerai', '/wiki/Mount_Jerai'),
('Mount Meron', '/wiki/Mount_Meron'),
('Doi Ian', '/wiki/Doi_Ian'),
('Mount Diablo', '/wiki/Mount_Diablo'),
('Bidean nam Bian', '/wiki/Bidean_nam_Bian'),
('Monte Musinè', '/wiki/Monte_Musin%C3%A8'),
('Brocken', '/wiki/Brocken'),
('Mount Aix', '/w/index.php?title=Mount_Aix&action=edit&redlink=1'),
('Victoria Peak', '/wiki/Victoria_Peak_(Belize)'),
('Snowdon', '/wiki/Snowdon'),
('Tafelberg', '/wiki/Table_Mountain'),
('Flattop Mountain', '/wiki/Flattop_Mountain_(Alaska)'),
('Uummannaq', '/wiki/Uummannaq_(mountain)'),
('White Butte', '/wiki/White_Butte'),
('Liathach', '/wiki/Liathach'),
('Saka Haphong', '/wiki/Saka_Haphong'),
('Corrán Tuathail', '/wiki/Corr%C3%A1n_Tuathail'),
('Mount Ramon', '/wiki/Mount_Ramon'),
('Girnar', '/wiki/Girnar'),
('Buachaille Etive Mor', '/wiki/Buachaille_Etive_Mor'),
('Munboksan', '/wiki/Munboksan'),
('Kékes', '/wiki/K%C3%A9kes'),
('Mount Belumut', '/wiki/Mount_Belumut'),
('Old Rag Mountain', '/wiki/Old_Rag_Mountain'),
('Magura Priei', '/w/index.php?title=Magura_Priei&action=edit&redlink=1'),
('Sgurr Dearg', '/wiki/Sgurr_Dearg'),
('Mount Sizer', '/wiki/Mount_Sizer'),
('Mount Valin', '/wiki/Mount_Valin'),
('Hyangnosan', '/wiki/Hyangnosan'),
('Scafell Pike', '/wiki/Scafell_Pike'),
('Mount Edgecumbe', '/wiki/Mount_Edgecumbe_(Alaska)'),
('North Mountain (Catskills)', '/wiki/North_Mountain_(Catskills)'),
('Doli Gutta', '/wiki/Doli_Gutta'),
('Mount Monadnock', '/wiki/Mount_Monadnock'),
('Tai Mo Shan', '/wiki/Tai_Mo_Shan'),
('Helvellyn', '/wiki/Helvellyn'),
('El Cerro del Aripo', '/wiki/El_Cerro_del_Aripo'),
('El Tucuche', '/wiki/El_Tucuche'),
('Lantau Peak', '/wiki/Lantau_Peak'),
('Betlingchhip', '/wiki/Betlingchhip'),
('Jampui Hills', '/wiki/Jampui_Hills'),
('Kaimondake volcano', '/wiki/Kaimondake_volcano'),
('San Salvatore', '/wiki/Monte_San_Salvatore'),
('Pantokrator', '/wiki/Mount_Pantokrator'),
('Baekunsan', '/wiki/Baekunsan'),
('Mount Gerizim', '/wiki/Mount_Gerizim'),
('Sunset Peak', '/wiki/Sunset_Peak_(Hong_Kong)'),
('Mount Taylor', '/wiki/Mount_Taylor_(Australian_Capital_Territory)'),
('Slaíbh Domhnaírt', '/w/index.php?title=Sla%C3%ADbh_Domhna%C3%ADrt&action=edit&redlink=1'),
('Tinakula', '/wiki/Tinakula'),
('Muntele Cetatuia', '/w/index.php?title=Muntele_Cetatuia&action=edit&redlink=1'),
('Mount Magazine', '/wiki/Mount_Magazine'),
('Hoemunsan', '/wiki/Hoemunsan'),
('Drocea', '/w/index.php?title=Drocea&action=edit&redlink=1'),
('Mount Carleton', '/wiki/Mount_Carleton'),
('Mount Santubong', '/wiki/Mount_Santubong'),
('Gros Morne', '/wiki/Gros_Morne,_Newfoundland'),
('Clisham', '/wiki/Clisham'),
('Mount Tamalpais', '/wiki/Mount_Tamalpais'),
('Gyemyeongsan', '/wiki/Gyemyeongsan'),
('Mount Boucherie', '/wiki/Mount_Boucherie'),
('Daeunsan', '/wiki/Daeunsan'),
('Ben Cleuch', '/wiki/Ben_Cleuch'),
('Gaseopsan', '/wiki/Gaseopsan'),
('Pu‘u ‘Ō‘ō', '/wiki/Pu%E2%80%98u_%E2%80%98%C5%8C%E2%80%98%C5%8D'),
('Signal de Botrange', '/wiki/Signal_de_Botrange'),
('Ishpatina Ridge', '/wiki/Ishpatina_Ridge'),
('Galgisan', '/wiki/Galgisan'),
('Delphi', '/wiki/Delphi'),
('Qalorujoorneq', '/wiki/Qalorujoorneq'),
('Maple Mountain', '/wiki/Maple_Mountain_(Ontario)'),
('Masaya', '/wiki/Masaya'),
('Moel Eilio', '/wiki/Moel_Eilio'),
('High Willhays', '/wiki/High_Willhays'),
('Munsusan (Ulsan)', '/wiki/Munsusan_(Ulsan)'),
('Mount Takao', '/wiki/Mount_Takao'),
('Sikjangsan', '/wiki/Sikjangsan'),
('Forbordsfjellet', '/wiki/Forbordsfjellet'),
('Gwanggyosan', '/wiki/Gwanggyosan'),
('Mount Pond', '/wiki/Mount_Pond'),
('Mount Tabor', '/wiki/Mount_Tabor'),
('Monte Conero', '/wiki/Monte_Conero'),
('Gyeryongsan', '/wiki/Gyeryongsan_(South_Gyeongsang_Province)'),
('Palasip Qaqqaa', '/wiki/Palasip_Qaqqaa'),
('Namamsan', '/wiki/Namamsan'),
('Taum Sauk Mountain', '/wiki/Taum_Sauk_Mountain'),
('Great Mell Fell', '/wiki/Great_Mell_Fell'),
('Geomdansan (Seongnam)', '/wiki/Geomdansan_(Seongnam)'),
('Yeonhwasan', '/wiki/Yeonhwasan'),
('Heukseongsan', '/wiki/Heukseongsan'),
('Avala', '/wiki/Avala'),
('Little Si', '/wiki/Little_Si'),
('Tutuiatu Peak', '/w/index.php?title=Tutuiatu_Peak&action=edit&redlink=1'),
("Pu'u Moaulanui", '/w/index.php?title=Pu%27u_Moaulanui&action=edit&redlink=1'),
('Blue Mountain', '/wiki/Blue_Mountain_(Ontario)'),
('Muryongsan (Ulsan)', '/wiki/Muryongsan_(Ulsan)'),
('Dongdaesan (Ulsan)', '/wiki/Dongdaesan_(Ulsan)'),
('Diamond Hill', '/wiki/Diamond_Hill_(Ireland)'),
('Storm King Mountain', '/wiki/Storm_King_Mountain_(New_York)'),
('Gyeyangsan', '/wiki/Gyeyangsan'),
('Loughrigg Fell', '/wiki/Loughrigg_Fell'),
('Mount Kinka (Gifu)', '/wiki/Mount_Kinka_(Gifu)'),
('Vaalserberg', '/wiki/Vaalserberg'),
('Suur Munamägi', '/wiki/Suur_Munam%C3%A4gi'),
('Aukštojas', '/wiki/Auk%C5%A1tojas_Hill'),
('Kruopinė', '/wiki/Kruopin%C4%97_Hill'),
('Juozapinė', '/wiki/Juozapin%C4%97_Hill'),
('Qixia Mountain', '/wiki/Qixia_Mountain'),
('Hwajangsan', '/wiki/Hwajangsan'),
('Potolaka/Putuo Shan', '/wiki/Mount_Putuo'),
('Westmacott', '/w/index.php?title=Mount_WestmacottMount&action=edit&redlink=1'),
('Jerimoth Hill', '/wiki/Jerimoth_Hill'),
('Diamond Head', '/wiki/Diamond_Head,_Hawaii'),
('Yeomposan', '/wiki/Yeomposan'),
('Hamwolsan', '/wiki/Hamwolsan'),
('Macau', '/wiki/Macau'),
('Britton Hill', '/wiki/Britton_Hill'),
('Mount Tenpō', '/wiki/Mount_Tenp%C5%8D'),
('Tianzhong Mountain', '/wiki/Tianzhong_Mountain'),
]
