# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarthImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permalink', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('preview_image_url', models.CharField(max_length=255)),
                ('base64_encoded_image', models.TextField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('subreddit_name', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('ups', models.IntegerField(default=0)),
                ('downs', models.IntegerField(default=0)),
                ('num_comments', models.IntegerField(default=0)),
                ('created_raw', models.DateField(max_length=255)),
            ],
        ),
    ]
