# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthimage',
            name='created_raw',
            field=models.CharField(max_length=255),
        ),
    ]
