# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170731_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuerySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_identifier', models.CharField(max_length=255)),
                ('query_keywords_title', models.TextField(null=True)),
                ('score_threshold_operand', models.CharField(choices=[('ge', 'Greater than'), ('le', 'Less than')], max_length=5)),
                ('score_threshold', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='earthimage',
            name='cleaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='earthimage',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
