# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170803_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthimage',
            name='original_source',
            field=models.BooleanField(default=False),
        ),
    ]
