# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_earthimage_original_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthimage',
            name='image_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='earthimage',
            name='permalink',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='earthimage',
            name='preferred_image_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='earthimage',
            name='preview_image_url',
            field=models.URLField(max_length=255),
        ),
    ]
