# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170803_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthimage',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='earthimage',
            name='permalink',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='earthimage',
            name='preferred_image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='earthimage',
            name='preview_image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='earthimage',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
