# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170803_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysetting',
            name='score_type',
            field=models.CharField(choices=[('score', 'Score'), ('downs', 'Downvotes'), ('ups', 'Upvotes')], default='score', max_length=100),
        ),
        migrations.AlterField(
            model_name='querysetting',
            name='score_threshold_operand',
            field=models.CharField(choices=[('ge', 'Greater than'), ('le', 'Less than')], default='ge', max_length=5),
        ),
    ]
