# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170804_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthimage',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='earthimage',
            name='resolution_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='earthimage',
            name='resolution_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='querysetting',
            name='query_keywords_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='querysetting',
            name='score_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='querysetting',
            name='score_threshold_operand',
            field=models.CharField(choices=[('gte', 'Greater than'), ('lte', 'Less than')], default='gte', max_length=5),
        ),
    ]
