# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170804_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthimage',
            name='raw_title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
