# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_earthimage_raw_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earthimage',
            old_name='public',
            new_name='is_public',
        ),
        migrations.AddField(
            model_name='querysetting',
            name='resolution_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='querysetting',
            name='resolution_threshold_operand',
            field=models.CharField(choices=[('width', 'Width'), ('height', 'Height')], default='width', max_length=8),
        ),
    ]
