# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170804_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysetting',
            name='resolution_type',
            field=models.CharField(choices=[('width', 'Width'), ('height', 'Height')], default='width', max_length=8),
        ),
        migrations.AlterField(
            model_name='querysetting',
            name='resolution_threshold_operand',
            field=models.CharField(choices=[('gte', 'Greater than'), ('lte', 'Less than')], default='gte', max_length=8),
        ),
    ]
