# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170804_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysetting',
            name='history',
            field=models.CharField(default='', max_length=255),
        ),
    ]
