# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_querysetting_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('global', 'Global'), ('specific', 'Source specific')], default='global', max_length=20)),
                ('source', models.CharField(blank=True, choices=[('reddit', 'reddit.com/r/Earth'), ('apod', "NASA's Astronomy Picture of the Day")], max_length=20)),
                ('filter_class', models.CharField(choices=[('query', 'By keyword in title filter'), ('resolution', 'Resolution filter'), ('score', 'Voting filter')], max_length=10)),
                ('arguments', models.CharField(max_length=255)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.QuerySetting')),
            ],
        ),
    ]
