# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='source',
            field=models.CharField(blank=True, choices=[('reddit', 'reddit.com/r/Earth'), ('apod', "NASA's Astronomy Picture of the Day")], default='', max_length=20),
        ),
    ]
