# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20170807_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysetting',
            name='contain_data_sources',
            field=models.CharField(default='', max_length=255),
        ),
    ]
