# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_querysetting_device_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EarthImage')),
            ],
        ),
        migrations.AddField(
            model_name='querysetting',
            name='relative_frequency',
            field=models.CharField(default='', max_length=20),
        ),
    ]
