# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20170816_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysetting',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
