# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20171212_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EarthImage')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.QuerySetting')),
            ],
        ),
    ]
