# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-06 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_favoriteimageitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthimage',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='earthimage',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='querysetting',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='querysetting',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
