# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_favoriteimageitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=12, max_digits=16)),
                ('long', models.DecimalField(decimal_places=12, max_digits=16)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(null=True)),
                ('google_maps_url', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='earthimage',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Location'),
        ),
    ]
