# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-15 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180114_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthimage',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='earthimage',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
