# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-06 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180115_0635'),
        ('api', '0025_auto_20180506_0512'),
    ]

    operations = [
    ]
