# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-06 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20180506_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysetting',
            name='only_favorites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='querysetting',
            name='only_favorites_own',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='earthimage',
            name='source',
            field=models.CharField(choices=[('all', 'all'), ('reddit', 'reddit.com/r/Earth'), ('apod', "NASA's Astronomy Picture of the Day"), ('wiki', 'Wikipedia Picture of the Day'), ('video', 'Video')], default='reddit', max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='source',
            field=models.CharField(blank=True, choices=[('all', 'all'), ('reddit', 'reddit.com/r/Earth'), ('apod', "NASA's Astronomy Picture of the Day"), ('wiki', 'Wikipedia Picture of the Day'), ('video', 'Video')], default='', max_length=20),
        ),
    ]
