# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-01 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180506_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthimage',
            name='special_css',
            field=models.CharField(default='', max_length=255),
        ),
    ]
